import Foundation
import SwiftParser
import SwiftSyntax

// MARK: - SwiftSyntaxEmitter

/// The primary Urkel v2 Swift code emitter.
///
/// Generates Swift source by composing structured string segments, then
/// validates every output file by parsing it with `SwiftParser`. Any
/// syntactically invalid output is caught before it reaches disk — the
/// parse tree is the correctness proof.
///
/// Usage:
/// ```swift
/// let files = try SwiftSyntaxEmitter().emit(file: urkelFile)
/// try files.stateMachine.write(to: url, atomically: true, encoding: .utf8)
/// ```
public struct SwiftSyntaxEmitter {
    public init() {}

    // MARK: - Public API

    /// Emits three source files for the given machine and validates each one.
    public func emit(file: UrkelFile) throws -> EmittedFiles {
        let sm  = emitStateMachineSource(for: file)
        let cl  = emitClientSource(for: file)
        let dep = emitDependencySource(for: file)
        try [sm, cl, dep].forEach { try validate(source: $0) }
        return EmittedFiles(stateMachine: sm, client: cl, dependency: dep)
    }

    // MARK: - Validation

    /// Parses `source` with `SwiftParser` and throws if any error nodes are present.
    public func validate(source: String) throws {
        let tree = Parser.parse(source: source)
        guard !tree.hasError else {
            throw SwiftSyntaxEmitterError.syntaxError("Generated source has syntax errors")
        }
    }

    // MARK: - File header

    private func fileHeader(for file: UrkelFile) -> String {
        let name = variableName(from: typeName(from: file.machineName))
        return "// Generated by Urkel — do not edit.\n// Source: \(name).urkel\n"
    }

    // MARK: - Imports

    private func emitImportsBlock(for file: UrkelFile) -> String {
        var names: [String] = ["Dependencies", "Foundation"]
        let extra = file.imports.map(\.name).filter { !names.contains($0) }
        names.append(contentsOf: extra)
        return names.map { "import \($0)" }.joined(separator: "\n")
    }

    // MARK: - Phase Namespace (US-5.2)

    func emitPhaseNamespace(for file: UrkelFile) -> String {
        let machineTN = typeName(from: file.machineName)
        let ns        = phaseNamespaceName(for: file.machineName)
        let cases = file.states.map { stateDecl -> String in
            switch stateDecl {
            case .simple(let state):
                let tn  = typeName(from: state.name)
                let doc = phaseDoc(for: state.kind)
                return "    \(doc)public enum \(tn) {}"
            case .compound(let compound):
                let tn = typeName(from: compound.name)
                let childCases = compound.children.map { child -> String in
                    let ctn = typeName(from: child.name)
                    return "        public enum \(ctn) {}"
                }.joined(separator: "\n")
                return "    public enum \(tn) {\n\(childCases)\n    }"
            }
        }.joined(separator: "\n")
        return """
        // MARK: - \(machineTN) Phases

        /// Phase markers for \(machineTN)Machine.
        /// Use `\(ns).Xxx` as the phantom `Phase` type argument.
        public enum \(ns) {
        \(cases)
        }
        """
    }

    private func phaseDoc(for kind: StateKind) -> String {
        switch kind {
        case .`init`:  return "/// The initial phase.\n    "
        case .final:   return "/// A terminal phase — no further transitions.\n    "
        case .state:   return ""
        }
    }

    // MARK: - State Data Enum (US-5.4/5.5)

    func emitStateDataEnum(for file: UrkelFile) -> String {
        let sdStates = statesWithData(in: file)
        guard !sdStates.isEmpty else { return "" }

        let machineTN = typeName(from: file.machineName)
        let enumName  = stateDataEnumName(for: file.machineName)
        var cases: [String] = ["    case none"]
        for state in sdStates {
            let cn     = stateDataCaseName(for: state.name)
            let fields = state.params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
            cases.append("    case \(cn)(\(fields))")
        }
        return """
        // MARK: - \(machineTN) State Data

        private enum \(enumName): Sendable {
        \(cases.joined(separator: "\n"))
        }
        """
    }

    func emitStateDataAccessors(for file: UrkelFile) -> String {
        let sdStates = statesWithData(in: file)
        guard !sdStates.isEmpty else { return "" }

        let machineT = machineTypeName(for: file.machineName)
        let phaseT   = phaseNamespaceName(for: file.machineName)

        return sdStates.map { state -> String in
            let stateT   = typeName(from: state.name)
            let caseName = stateDataCaseName(for: state.name)

            let properties = state.params.map { param -> String in
                let patternParts = state.params.map { p -> String in
                    p.label == param.label ? "let \(p.label)" : "_"
                }.joined(separator: ", ")
                return """
                    /// Available only in the `\(state.name)` phase.
                    public borrowing var \(param.label): \(param.typeExpr) {
                        guard case .\(caseName)(\(patternParts)) = _stateData else {
                            preconditionFailure("Emitter invariant: in \(state.name) phase but _stateData is \\(_stateData)")
                        }
                        return \(param.label)
                    }
                """
            }.joined(separator: "\n\n")

            return """
            extension \(machineT) where Phase == \(phaseT).\(stateT) {
            \(properties)
            }
            """
        }.joined(separator: "\n\n")
    }

    // MARK: - Machine Struct (US-5.2 + 5.4–5.7)

    func emitMachineStruct(for file: UrkelFile) -> String {
        let machineTN   = typeName(from: file.machineName)
        let structName  = machineTypeName(for: file.machineName)
        let hasContext  = file.contextType != nil
        let ctx         = file.contextType ?? "Void"
        let closureInfos = allTransitionClosureInfos(in: file)
        let actionNames  = uniqueActionNames(in: file)
        let guardNames   = uniqueGuardNames(in: file)
        let sdStates     = statesWithData(in: file)
        let hasStateData = !sdStates.isEmpty
        let sdEnumName   = stateDataEnumName(for: file.machineName)
        let hasTimerPhases = hasTimers(in: file)

        var lines: [String] = []
        lines.append("// MARK: - \(machineTN) State Machine")
        lines.append("")
        lines.append("""
        /// A type-safe, move-only \(machineTN) state machine.
        ///
        /// The current phase is encoded in the `Phase` phantom type parameter.
        /// Transition methods are only available in the matching phase —
        /// invalid transitions are compile-time errors.
        public struct \(structName)<Phase>: ~Copyable, Sendable {
        """)

        if hasContext {
            lines.append("    fileprivate let _context: \(ctx)")
        }
        if hasStateData {
            lines.append("    fileprivate let _stateData: \(sdEnumName)")
        }
        if hasTimerPhases {
            lines.append("    nonisolated(unsafe) fileprivate var _timerTask: Task<Void, Never>?")
        }
        for info in closureInfos {
            lines.append("    fileprivate let \(info.propName): \(info.closureTypeStr(ctx: hasContext ? ctx : nil))")
        }
        for name in actionNames {
            let prop = actionPropertyName(for: name)
            let t    = hasContext ? "@Sendable (\(ctx)) async -> Void" : "@Sendable () async -> Void"
            lines.append("    fileprivate let \(prop): \(t)")
        }
        for name in guardNames {
            let prop = guardPropertyName(for: name)
            let t    = hasContext ? "@Sendable (\(ctx)) async -> Bool" : "@Sendable () async -> Bool"
            lines.append("    fileprivate let \(prop): \(t)")
        }

        // Sub-machine properties (US-5.11)
        let subImports = subMachineImports(in: file)
        for imp in subImports {
            let varN   = stateCaseName(for: imp.name)
            let stateT = stateEnumTypeName(for: imp.name)
            let typN   = typeName(from: imp.name)
            lines.append("    fileprivate var _\(varN)State: \(stateT)?")
            lines.append("    fileprivate let _make\(typN): @Sendable () -> \(stateT)")
        }

        // Compound inner state properties (US-5.12)
        for compound in compoundStates(in: file) {
            let varN      = stateCaseName(for: compound.name)
            let innerEnum = innerStateEnumName(for: compound.name, machineName: file.machineName)
            lines.append("    fileprivate var _\(varN)InnerState: \(innerEnum)?")
        }

        // init
        var initParts: [String] = []
        if hasContext { initParts.append("        _context: \(ctx)") }
        if hasStateData { initParts.append("        _stateData: \(sdEnumName) = .none") }
        if hasTimerPhases { initParts.append("        _timerTask: Task<Void, Never>? = nil") }
        for info in closureInfos {
            initParts.append("        \(info.propName): @escaping \(info.closureTypeStr(ctx: hasContext ? ctx : nil))")
        }
        for name in actionNames {
            let prop = actionPropertyName(for: name)
            let t    = hasContext ? "@Sendable (\(ctx)) async -> Void" : "@Sendable () async -> Void"
            initParts.append("        \(prop): @escaping \(t)")
        }
        for name in guardNames {
            let prop = guardPropertyName(for: name)
            let t    = hasContext ? "@Sendable (\(ctx)) async -> Bool" : "@Sendable () async -> Bool"
            initParts.append("        \(prop): @escaping \(t)")
        }
        // Sub-machine init params (US-5.11)
        for imp in subImports {
            let varN   = stateCaseName(for: imp.name)
            let stateT = stateEnumTypeName(for: imp.name)
            let typN   = typeName(from: imp.name)
            initParts.append("        _\(varN)State: \(stateT)? = nil")
            initParts.append("        _make\(typN): @escaping @Sendable () -> \(stateT)")
        }
        // Compound inner state init params (US-5.12)
        for compound in compoundStates(in: file) {
            let varN      = stateCaseName(for: compound.name)
            let innerEnum = innerStateEnumName(for: compound.name, machineName: file.machineName)
            initParts.append("        _\(varN)InnerState: \(innerEnum)? = nil")
        }

        lines.append("")
        lines.append("    internal init(")
        lines.append(initParts.joined(separator: ",\n"))
        lines.append("    ) {")
        if hasContext { lines.append("        self._context = _context") }
        if hasStateData { lines.append("        self._stateData = _stateData") }
        if hasTimerPhases { lines.append("        self._timerTask = _timerTask") }
        for info in closureInfos { lines.append("        self.\(info.propName) = \(info.propName)") }
        for name in actionNames {
            let p = actionPropertyName(for: name)
            lines.append("        self.\(p) = \(p)")
        }
        for name in guardNames {
            let p = guardPropertyName(for: name)
            lines.append("        self.\(p) = \(p)")
        }
        // Sub-machine assignments (US-5.11)
        for imp in subImports {
            let varN = stateCaseName(for: imp.name)
            let typN = typeName(from: imp.name)
            lines.append("        self._\(varN)State = _\(varN)State")
            lines.append("        self._make\(typN) = _make\(typN)")
        }
        // Compound inner state assignments (US-5.12)
        for compound in compoundStates(in: file) {
            let varN = stateCaseName(for: compound.name)
            lines.append("        self._\(varN)InnerState = _\(varN)InnerState")
        }
        lines.append("    }")

        if hasContext {
            lines.append("")
            lines.append("""
                /// Read-only access to the context without consuming the machine.
                public borrowing func withContext<R>(
                    _ body: (borrowing \(ctx)) throws -> R
                ) rethrows -> R {
                    try body(_context)
                }
            """)
        }

        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Transition Extensions (US-5.2 + 5.6–5.9)

    func emitTransitionExtensions(for file: UrkelFile) -> String {
        let machineT = machineTypeName(for: file.machineName)
        let phaseT   = phaseNamespaceName(for: file.machineName)

        return file.simpleStates.compactMap { state -> String? in
            guard state.kind != .final else { return nil }
            let allOut = outgoing(from: state.name, in: file)
            guard !allOut.isEmpty else { return nil }

            let stateT = typeName(from: state.name)
            var methods: [String] = []

            // 1. Standard transitions grouped by event name
            let standard = allOut.filter {
                guard case .event(_) = $0.event else { return false }
                return $0.arrow == .standard
            }
            var seenEvents = Set<String>()
            for t in standard {
                guard case .event(let ev) = t.event else { continue }
                guard seenEvents.insert(ev.name).inserted else { continue }
                let group = standard.filter {
                    guard case .event(let sev) = $0.event else { return false }
                    return sev.name == ev.name
                }
                let hasGuards = group.contains { $0.guard != nil }
                if hasGuards {
                    methods.append(emitGuardedMethod(
                        event: ev.name,
                        params: ev.params.map { Parameter(label: $0.label, typeExpr: $0.typeExpr) },
                        group: group, sourceState: state.name, file: file))
                } else if let t = group.first, let dest = t.destination {
                    methods.append(emitSimpleMethod(
                        t: t, sourceState: state.name, event: ev.name,
                        params: ev.params.map { Parameter(label: $0.label, typeExpr: $0.typeExpr) },
                        dest: dest.name, file: file))
                }
            }

            // 2. Internal in-place transitions (-*> with action, US-5.8)
            for t in allOut where t.arrow == .`internal` && t.isInPlaceHandler {
                if case .event(let ev) = t.event {
                    methods.append(emitInternalInPlaceMethod(
                        event: ev.name,
                        params: ev.params.map { Parameter(label: $0.label, typeExpr: $0.typeExpr) },
                        action: t.action, sourceState: state.name, file: file))
                }
            }

            // 3. Always / eventless transitions (US-5.9)
            let always = allOut.filter { if case .always = $0.event { return true }; return false }
            if !always.isEmpty {
                methods.append(emitAlwaysMethod(transitions: always, sourceState: state.name, file: file))
            }

            // 4. Timer transitions (US-5.10)
            let timerTransitions = allOut.filter { if case .timer(_) = $0.event { return true }; return false }
            if !timerTransitions.isEmpty {
                methods.append(contentsOf: emitTimerMethods(transitions: timerTransitions, sourceState: state.name, file: file))
            }

            guard !methods.isEmpty else { return nil }

            return """
            // MARK: - \(machineT)<\(stateT)>

            extension \(machineT) where Phase == \(phaseT).\(stateT) {
            \(methods.joined(separator: "\n\n"))
            }
            """
        }.joined(separator: "\n\n")
    }

    // MARK: - Simple transition method (no guards)

    private func emitSimpleMethod(
        t: TransitionStmt,
        sourceState: String,
        event: String,
        params: [Parameter],
        dest: String,
        file: UrkelFile
    ) -> String {
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let hasCtx     = file.contextType != nil
        let resolvedDest = resolveCompoundDest(dest, in: file)
        let returnT    = "\(machineT)<\(phasePath(for: resolvedDest, in: file))>"
        let paramSig   = params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
        let callArgs   = params.map(\.label).joined(separator: ", ")
        let propName   = transitionPropName(for: t, in: file)
        let doc        = t.docComments.isEmpty
            ? "    /// Transitions from `\(sourceState)` to `\(dest)`."
            : t.docComments.map { "    /// \($0.text)" }.joined(separator: "\n")

        var body: [String] = []

        // Cancel timer if this source state has timer transitions (US-5.10)
        if statesWithTimers(in: file).contains(where: { $0.name == sourceState }) {
            body.append("        _timerTask?.cancel()")
        }

        // @exit hooks
        for a in exitActions(for: sourceState, in: file) {
            body.append("        await \(actionPropertyName(for: a))(\(hasCtx ? "_context" : ""))")
        }

        // Fork: instantiate sub-machine (US-5.11)
        if let fork = t.fork {
            let typN = typeName(from: fork.machine)
            let varN = stateCaseName(for: fork.machine)
            body.append("        let \(varN) = _make\(typN)()")
        }

        // transition
        if hasCtx {
            let callExpr = callArgs.isEmpty ? "_context" : "_context, \(callArgs)"
            body.append("        let next = try await \(propName)(\(callExpr))")
        } else if !params.isEmpty {
            body.append("        try await \(propName)(\(callArgs))")
        }

        // transition actions
        let nextOrCtx = hasCtx ? "next" : ""
        for a in (t.action?.actions ?? []) {
            body.append("        await \(actionPropertyName(for: a))(\(nextOrCtx))")
        }

        // @entry hooks
        for a in entryActions(for: dest, in: file) {
            body.append("        await \(actionPropertyName(for: a))(\(nextOrCtx))")
        }

        // return
        let constructArgs = machineConstructionArgs(destStateName: dest, file: file, indent: 12, forkedMachineName: t.fork?.machine)
        body.append("        return \(returnT)(\n\(constructArgs)\n        )")

        let throwsKw = hasCtx ? " async throws" : ""
        return """
        \(doc)
            public consuming func \(event)(\(paramSig))\(throwsKw) -> \(returnT) {
        \(body.joined(separator: "\n"))
            }
        """
    }

    // MARK: - Guarded transition method (US-5.7)

    private func emitGuardedMethod(
        event: String,
        params: [Parameter],
        group: [TransitionStmt],
        sourceState: String,
        file: UrkelFile
    ) -> String {
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let stateEnumT = stateEnumTypeName(for: file.machineName)
        let hasCtx     = file.contextType != nil
        let paramSig   = params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
        let callArgs   = params.map(\.label).joined(separator: ", ")
        let throwsKw   = hasCtx ? " async throws" : ""
        let nextOrCtx  = hasCtx ? "next" : ""

        var branches: [String] = []
        var hasElse = false

        for t in group {
            guard let dest = t.destination else { continue }
            let destT     = typeName(from: dest.name)
            let destCase  = stateCaseName(for: dest.name)
            let propName  = transitionPropName(for: t, in: file)

            var branchBody: [String] = []
            if hasCtx {
                let callExpr = callArgs.isEmpty ? "_context" : "_context, \(callArgs)"
                branchBody.append("            let next = try await \(propName)(\(callExpr))")
            }
            for a in (t.action?.actions ?? []) {
                branchBody.append("            await \(actionPropertyName(for: a))(\(nextOrCtx))")
            }
            for a in entryActions(for: dest.name, in: file) {
                branchBody.append("            await \(actionPropertyName(for: a))(\(nextOrCtx))")
            }
            let constructArgs = machineConstructionArgs(destStateName: dest.name, file: file, indent: 16)
            let machineExpr = "\(machineT)<\(phaseT).\(destT)>(\n\(constructArgs)\n            )"
            branchBody.append("            return .\(destCase)(\(machineExpr))")

            let branchCode = branchBody.joined(separator: "\n")

            switch t.guard {
            case .none:
                // Unguarded branch in a guarded group — treat as else
                branches.append("        } else {\n\(branchCode)")
                hasElse = true
            case .named(let n):
                let pred = "await \(guardPropertyName(for: n))(\(hasCtx ? "_context" : ""))"
                if branches.isEmpty {
                    branches.append("        if \(pred) {\n\(branchCode)")
                } else {
                    branches.append("        } else if \(pred) {\n\(branchCode)")
                }
            case .negated(let n):
                let pred = "!(await \(guardPropertyName(for: n))(\(hasCtx ? "_context" : "")))"
                if branches.isEmpty {
                    branches.append("        if \(pred) {\n\(branchCode)")
                } else {
                    branches.append("        } else if \(pred) {\n\(branchCode)")
                }
            case .else:
                branches.append("        } else {\n\(branchCode)")
                hasElse = true
            }
        }

        if !hasElse {
            // Safety fallback — should not happen in valid machines
            branches.append("        } else {\n            fatalError(\"Urkel emitter: no guard matched for '\(event)' in '\(sourceState)'\")")
        }

        let branchStr = branches.joined(separator: "\n") + "\n        }"

        var exitLines: [String] = []
        // Cancel timer if source state has timer transitions (US-5.10)
        if statesWithTimers(in: file).contains(where: { $0.name == sourceState }) {
            exitLines.append("        _timerTask?.cancel()")
        }
        for a in exitActions(for: sourceState, in: file) {
            exitLines.append("        await \(actionPropertyName(for: a))(\(hasCtx ? "_context" : ""))")
        }
        let exitBlock = exitLines.isEmpty ? "" : exitLines.joined(separator: "\n") + "\n"

        return """
            /// Handles `\(event)` — pattern-match the result for each guard branch.
            public consuming func \(event)(\(paramSig))\(throwsKw) -> \(stateEnumT) {
        \(exitBlock)\(branchStr)
            }
        """
    }

    // MARK: - Internal in-place method (US-5.8)

    private func emitInternalInPlaceMethod(
        event: String,
        params: [Parameter],
        action: ActionClause?,
        sourceState: String,
        file: UrkelFile
    ) -> String {
        let hasCtx   = file.contextType != nil
        let paramSig = params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
        var body: [String] = []
        for a in (action?.actions ?? []) {
            body.append("        await \(actionPropertyName(for: a))(\(hasCtx ? "_context" : ""))")
        }
        let bodyStr = body.isEmpty ? "        // no-op" : body.joined(separator: "\n")
        return """
            /// Handles `\(event)` in-place; machine remains in `\(sourceState)`.
            public borrowing func \(event)(\(paramSig)) async {
        \(bodyStr)
            }
        """
    }

    // MARK: - Always / eventless transition (US-5.9)

    private func emitAlwaysMethod(
        transitions: [TransitionStmt],
        sourceState: String,
        file: UrkelFile
    ) -> String {
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let stateEnumT = stateEnumTypeName(for: file.machineName)
        let hasCtx     = file.contextType != nil
        let hasGuards  = transitions.contains { $0.guard != nil }
        let nextOrCtx  = hasCtx ? "next" : ""

        if !hasGuards, let t = transitions.first, let dest = t.destination {
            // Unconditional always — returns specific phase
            let destT    = typeName(from: dest.name)
            let retT     = "\(machineT)<\(phaseT).\(destT)>"
            let propName = transitionPropName(for: t, in: file)
            var body: [String] = []
            if statesWithTimers(in: file).contains(where: { $0.name == sourceState }) {
                body.append("        _timerTask?.cancel()")
            }
            for a in exitActions(for: sourceState, in: file) {
                body.append("        await \(actionPropertyName(for: a))(\(hasCtx ? "_context" : ""))")
            }
            if hasCtx {
                body.append("        let next = try await \(propName)(_context)")
            }
            for a in (t.action?.actions ?? []) {
                body.append("        await \(actionPropertyName(for: a))(\(nextOrCtx))")
            }
            for a in entryActions(for: dest.name, in: file) {
                body.append("        await \(actionPropertyName(for: a))(\(nextOrCtx))")
            }
            let constructArgs = machineConstructionArgs(destStateName: dest.name, file: file, indent: 12)
            body.append("        return \(retT)(\n\(constructArgs)\n        )")
            let throwsKw = hasCtx ? " async throws" : ""
            return """
                /// Automatically transitions from `\(sourceState)` — call immediately after entering this phase.
                public consuming func autoTransition()\(throwsKw) -> \(retT) {
            \(body.joined(separator: "\n"))
                }
            """
        } else {
            // Guarded always — returns combined state enum
            var branches: [String] = []
            var hasElse = false
            for t in transitions {
                guard let dest = t.destination else { continue }
                let destT    = typeName(from: dest.name)
                let destCase = stateCaseName(for: dest.name)
                let propName = transitionPropName(for: t, in: file)
                var bBody: [String] = []
                if hasCtx {
                    bBody.append("            let next = try await \(propName)(_context)")
                }
                for a in (t.action?.actions ?? []) {
                    bBody.append("            await \(actionPropertyName(for: a))(\(nextOrCtx))")
                }
                for a in entryActions(for: dest.name, in: file) {
                    bBody.append("            await \(actionPropertyName(for: a))(\(nextOrCtx))")
                }
                let constructArgs = machineConstructionArgs(destStateName: dest.name, file: file, indent: 16)
                let machineExpr = "\(machineT)<\(phaseT).\(destT)>(\n\(constructArgs)\n            )"
                bBody.append("            return .\(destCase)(\(machineExpr))")
                let branchCode = bBody.joined(separator: "\n")
                switch t.guard {
                case .none, .else:
                    branches.append("        } else {\n\(branchCode)")
                    hasElse = true
                case .named(let n):
                    let pred = "await \(guardPropertyName(for: n))(\(hasCtx ? "_context" : ""))"
                    branches.append(branches.isEmpty
                        ? "        if \(pred) {\n\(branchCode)"
                        : "        } else if \(pred) {\n\(branchCode)")
                case .negated(let n):
                    let pred = "!(await \(guardPropertyName(for: n))(\(hasCtx ? "_context" : "")))"
                    branches.append(branches.isEmpty
                        ? "        if \(pred) {\n\(branchCode)"
                        : "        } else if \(pred) {\n\(branchCode)")
                }
            }
            if !hasElse {
                branches.append("        } else {\n            fatalError(\"Urkel: no always guard matched in '\(sourceState)'\")")
            }
            let branchStr = branches.joined(separator: "\n") + "\n        }"
            let throwsKw = hasCtx ? " async throws" : ""
            return """
                /// Evaluates `always` guards and transitions automatically.
                public consuming func autoTransition()\(throwsKw) -> \(stateEnumT) {
            \(branchStr)
                }
            """
        }
    }

    // MARK: - Combined State Enum

    func emitStateEnum(for file: UrkelFile) -> String {
        let machineTN  = typeName(from: file.machineName)
        let enumName   = stateEnumTypeName(for: file.machineName)
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let hasContext = file.contextType != nil

        let cases = file.states.map { stateDecl -> String in
            switch stateDecl {
            case .simple(let s):
                let tn = typeName(from: s.name)
                let c  = stateCaseName(for: s.name)
                return "    case \(c)(\(machineT)<\(phaseT).\(tn)>)"
            case .compound(let compound):
                let innerEnumN = innerStateEnumName(for: compound.name, machineName: file.machineName)
                let c = stateCaseName(for: compound.name)
                return "    case \(c)(\(innerEnumN))"
            }
        }.joined(separator: "\n")

        let initDecl: String = {
            guard let init_ = file.initState else { return "" }
            let tn = typeName(from: init_.name)
            let c  = stateCaseName(for: init_.name)
            return """

                /// Wraps an initial-phase machine.
                public init(_ initial: consuming \(machineT)<\(phaseT).\(tn)>) {
                    self = .\(c)(initial)
                }
            """
        }()

        let enumDecl = """
        // MARK: - \(machineTN) Combined State

        /// Runtime-erasure wrapper over all \(machineTN) phases.
        /// Use when the current phase is not statically known.
        public enum \(enumName): ~Copyable {
        \(cases)\(initDecl)
        }
        """

        let accessors = file.states.map { stateDecl -> String in
            switch stateDecl {
            case .simple(let s):
                let tn = typeName(from: s.name)
                let c  = stateCaseName(for: s.name)
                let mt = "\(machineT)<\(phaseT).\(tn)>"
                return """
                    public borrowing func with\(tn)<R>(
                        _ body: (borrowing \(mt)) throws -> R
                    ) rethrows -> R? {
                        guard case .\(c)(let m) = self else { return nil }
                        return try body(m)
                    }
                """
            case .compound(let compound):
                let tn = typeName(from: compound.name)
                let c  = stateCaseName(for: compound.name)
                let innerEnumN = innerStateEnumName(for: compound.name, machineName: file.machineName)
                return """
                    public borrowing func with\(tn)<R>(
                        _ body: (borrowing \(innerEnumN)) throws -> R
                    ) rethrows -> R? {
                        guard case .\(c)(let m) = self else { return nil }
                        return try body(m)
                    }
                """
            }
        }.joined(separator: "\n\n")

        // Only unguarded events get delegating methods on the combined state
        let delegatingMethods = allTransitionClosureInfos(in: file)
            .filter { info in
                // Only include if this event is unguarded from at least one source in top-level transitions
                file.transitionStmts.contains { t in
                    guard case .event(_) = t.event, t.arrow == .standard else { return false }
                    let propName = transitionPropName(for: t, in: file)
                    return propName == info.propName
                }
            }
            .map { info -> String in
                let paramSig  = info.params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
                let callArgs  = info.params.map { "\($0.label): \($0.label)" }.joined(separator: ", ")
                let switchCases = file.states.map { stateDecl -> String in
                    switch stateDecl {
                    case .compound(let compound):
                        let c_ = stateCaseName(for: compound.name)
                        return "        case .\(c_)(let m): return .\(c_)(m)"
                    case .simple(let s):
                        let c_ = stateCaseName(for: s.name)
                        let t  = outgoing(from: s.name, in: file).first { t in
                            guard case .event(let ev) = t.event else { return false }
                            return ev.name == info.event && t.arrow == .standard && t.guard == nil
                        }
                        if let t, let dest = t.destination {
                            // Check if destination is a compound state
                            if let compound = compoundStates(in: file).first(where: { $0.name == dest.name }) {
                                let innerEnumN = innerStateEnumName(for: compound.name, machineName: file.machineName)
                                let dc = stateCaseName(for: compound.name)
                                let initChild = compound.children.first(where: { $0.kind == .`init` }) ?? compound.children.first
                                if let child = initChild {
                                    let childCaseName = stateCaseName(for: child.name)
                                    let call = callArgs.isEmpty
                                        ? "try await m.\(info.event)()"
                                        : "try await m.\(info.event)(\(callArgs))"
                                    return "        case .\(c_)(let m): return .\(dc)(\(innerEnumN).\(childCaseName)(\(call)))"
                                } else {
                                    return "        case .\(c_)(let m): return .\(c_)(m)"
                                }
                            } else {
                                let dc   = stateCaseName(for: dest.name)
                                let call = callArgs.isEmpty
                                    ? "try await m.\(info.event)()"
                                    : "try await m.\(info.event)(\(callArgs))"
                                return "        case .\(c_)(let m): return .\(dc)(\(call))"
                            }
                        } else {
                            return "        case .\(c_)(let m): return .\(c_)(m)"
                        }
                    }
                }.joined(separator: "\n")

                if hasContext {
                    return """
                        /// Attempts `\(info.event)` from the current state. No-ops in states where it is not defined.
                        public consuming func \(info.event)(\(paramSig)) async throws -> \(enumName) {
                            switch consume self {
                    \(switchCases)
                            }
                        }
                    """
                } else {
                    return """
                        public consuming func \(info.event)(\(paramSig)) -> \(enumName) {
                            switch consume self {
                    \(switchCases)
                            }
                        }
                    """
                }
            }.joined(separator: "\n\n")

        let ext = """
        extension \(enumName) {

        \(accessors)

        \(delegatingMethods)
        }
        """

        return [enumDecl, ext].joined(separator: "\n\n")
    }

    // MARK: - Client Runtime (US-5.3 + 5.6–5.7)

    func emitClientRuntime(for file: UrkelFile) -> String {
        let runtimeN    = runtimeTypeName(for: file.machineName)
        let machineTN   = typeName(from: file.machineName)
        let hasContext   = file.contextType != nil
        let ctx          = file.contextType ?? "Void"
        let infos        = allTransitionClosureInfos(in: file)
        let actionNames  = uniqueActionNames(in: file)
        let guardNames   = uniqueGuardNames(in: file)
        let initParams   = file.initState?.params ?? []

        var lines: [String] = ["// MARK: - \(machineTN) Runtime Builder", ""]
        lines.append("/// Provides individual hooks for constructing a \(machineTN)Client.")
        lines.append("public struct \(runtimeN): Sendable {")

        if hasContext {
            let pTypes = initParams.map(\.typeExpr).joined(separator: ", ")
            let initType = pTypes.isEmpty
                ? "@Sendable () -> \(ctx)"
                : "@Sendable (\(pTypes)) -> \(ctx)"
            lines.append("    public typealias InitialContextBuilder = \(initType)")
        }
        for info in infos {
            lines.append("    public typealias \(info.aliasName) = \(info.closureTypeStr(ctx: hasContext ? ctx : nil))")
        }
        for name in actionNames {
            let alias = typeName(from: name) + "Action"
            let t     = hasContext ? "@Sendable (\(ctx)) async -> Void" : "@Sendable () async -> Void"
            lines.append("    public typealias \(alias) = \(t)")
        }
        for name in guardNames {
            let alias = typeName(from: name) + "Guard"
            let t     = hasContext ? "@Sendable (\(ctx)) async -> Bool" : "@Sendable () async -> Bool"
            lines.append("    public typealias \(alias) = \(t)")
        }

        if hasContext { lines.append("    public let initialContext: InitialContextBuilder") }
        for info in infos { lines.append("    public let \(info.runtimePropName): \(info.aliasName)") }
        for name in actionNames {
            let alias = typeName(from: name) + "Action"
            let prop  = variableName(from: alias)
            lines.append("    public let \(prop): \(alias)")
        }
        for name in guardNames {
            let alias = typeName(from: name) + "Guard"
            let prop  = variableName(from: alias)
            lines.append("    public let \(prop): \(alias)")
        }

        // init
        var initArgs: [String] = []
        if hasContext { initArgs.append("        initialContext: @escaping InitialContextBuilder") }
        for info in infos { initArgs.append("        \(info.runtimePropName): @escaping \(info.aliasName)") }
        for name in actionNames {
            let alias = typeName(from: name) + "Action"
            let prop  = variableName(from: alias)
            initArgs.append("        \(prop): @escaping \(alias)")
        }
        for name in guardNames {
            let alias = typeName(from: name) + "Guard"
            let prop  = variableName(from: alias)
            initArgs.append("        \(prop): @escaping \(alias)")
        }
        lines.append("")
        lines.append("    public init(")
        lines.append(initArgs.joined(separator: ",\n"))
        lines.append("    ) {")
        if hasContext { lines.append("        self.initialContext = initialContext") }
        for info in infos { lines.append("        self.\(info.runtimePropName) = \(info.runtimePropName)") }
        for name in actionNames {
            let alias = typeName(from: name) + "Action"
            let prop  = variableName(from: alias)
            lines.append("        self.\(prop) = \(prop)")
        }
        for name in guardNames {
            let alias = typeName(from: name) + "Guard"
            let prop  = variableName(from: alias)
            lines.append("        self.\(prop) = \(prop)")
        }
        lines.append("    }")
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Client Struct + Extension (US-5.3 + 5.6–5.7)

    func emitClientStruct(for file: UrkelFile) -> String {
        let clientN    = clientTypeName(for: file.machineName)
        let machineTN  = typeName(from: file.machineName)
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let runtimeN   = runtimeTypeName(for: file.machineName)
        let initState  = file.initState?.name ?? "Initial"
        let initTN     = typeName(from: initState)
        let hasContext = file.contextType != nil
        let ctx        = file.contextType ?? "Void"
        let initParams = file.initState?.params ?? []
        let infos      = allTransitionClosureInfos(in: file)
        let actionNames = uniqueActionNames(in: file)
        let guardNames  = uniqueGuardNames(in: file)
        let sdStates    = statesWithData(in: file)
        let hasSD       = !sdStates.isEmpty
        let keyName    = dependencyKeyName(for: file.machineName)

        let pTypes  = initParams.map(\.typeExpr).joined(separator: ", ")
        let retT    = "\(machineT)<\(phaseT).\(initTN)>"
        let subImports = subMachineImports(in: file)
        let factoryT: String
        if subImports.isEmpty {
            if pTypes.isEmpty {
                factoryT = "@Sendable () -> \(retT)"
            } else {
                factoryT = "@Sendable (\(pTypes)) -> \(retT)"
            }
        } else {
            var paramParts: [String] = []
            if !pTypes.isEmpty { paramParts.append(pTypes) }
            for imp in subImports {
                let stateT = stateEnumTypeName(for: imp.name)
                paramParts.append("@Sendable () -> \(stateT)")
            }
            factoryT = "@Sendable (\(paramParts.joined(separator: ", "))) -> \(retT)"
        }

        var noopProps: [String] = []
        if hasContext {
            for info in infos {
                let count   = info.params.count
                let ignores = count == 0 ? "ctx, _ in ctx" : "ctx, " + (0..<count).map { _ in "_" }.joined(separator: ", ") + " in ctx"
                noopProps.append("            \(info.propName): { \(ignores) }")
            }
        } else {
            for info in infos {
                noopProps.append("            \(info.propName): { }")
            }
        }
        for name in actionNames {
            let prop = actionPropertyName(for: name)
            noopProps.append("            \(prop): { \(hasContext ? "_ in" : "_ in") }")
        }
        for name in guardNames {
            let prop = guardPropertyName(for: name)
            noopProps.append("            \(prop): { \(hasContext ? "_ in " : "")false }")
        }
        for imp in subImports {
            let varN = stateCaseName(for: imp.name)
            let typN = typeName(from: imp.name)
            noopProps.append("            _\(varN)State: nil")
            noopProps.append("            _make\(typN): make\(typN)")
        }
        for compound in compoundStates(in: file) {
            let varN = stateCaseName(for: compound.name)
            noopProps.append("            _\(varN)InnerState: nil")
        }

        let subFactoryParams = subImports.map { "make\(typeName(from: $0.name))" }.joined(separator: ", ")
        let noopIgnoreBase  = initParams.isEmpty ? "" : "_"
        let noopIgnoreParts = ([noopIgnoreBase].filter { !$0.isEmpty } + subImports.map { "make\(typeName(from: $0.name))" }).filter { !$0.isEmpty }
        let noopIgnore: String = noopIgnoreParts.isEmpty ? "" : "\(noopIgnoreParts.joined(separator: ", ")) in\n            "
        let noopCtxLine = hasContext ? "let _ctx = \(ctx)()\n            " : ""
        let noopCtxArg  = hasContext ? "            _context: _ctx,\n" : ""
        let noopSDLine  = hasSD ? "            _stateData: .none,\n" : ""
        let noopPropsStr = noopProps.isEmpty ? "" : "\n" + noopProps.joined(separator: ",\n") + "\n        "
        let noopMachine = "\(retT)(\n\(noopCtxArg)\(noopSDLine)\(noopPropsStr.isEmpty ? "        " : noopPropsStr))"

        // fromRuntime
        let fromRuntimePNames = initParams.map(\.label).joined(separator: ", ")
        let fromRuntimePartsAll = (fromRuntimePNames.isEmpty ? [] : [fromRuntimePNames]) + subImports.map { "make\(typeName(from: $0.name))" }
        let fromRuntimeSig    = fromRuntimePartsAll.isEmpty ? "" : "\(fromRuntimePartsAll.joined(separator: ", ")) in\n            "
        let fromRuntimeCtx    = hasContext ? "let context = runtime.initialContext(\(fromRuntimePNames))\n            " : ""
        var fromRuntimeForwards: [String] = []
        if hasContext { fromRuntimeForwards.append("                _context: context") }
        if hasSD      { fromRuntimeForwards.append("                _stateData: .none") }
        for info in infos {
            fromRuntimeForwards.append("                \(info.propName): runtime.\(info.runtimePropName)")
        }
        for name in actionNames {
            let prop  = actionPropertyName(for: name)
            let alias = typeName(from: name) + "Action"
            let rProp = variableName(from: alias)
            fromRuntimeForwards.append("                \(prop): runtime.\(rProp)")
        }
        for name in guardNames {
            let prop  = guardPropertyName(for: name)
            let alias = typeName(from: name) + "Guard"
            let rProp = variableName(from: alias)
            fromRuntimeForwards.append("                \(prop): runtime.\(rProp)")
        }
        for imp in subImports {
            let varN = stateCaseName(for: imp.name)
            let typN = typeName(from: imp.name)
            fromRuntimeForwards.append("                _\(varN)State: nil")
            fromRuntimeForwards.append("                _make\(typN): make\(typN)")
        }
        for compound in compoundStates(in: file) {
            let varN = stateCaseName(for: compound.name)
            fromRuntimeForwards.append("                _\(varN)InnerState: nil")
        }
        let fromRuntimeMachine = fromRuntimeForwards.isEmpty
            ? (hasContext ? "\(retT)(\n                _context: context\n            )" : "\(retT)()")
            : "\(retT)(\n\(fromRuntimeForwards.joined(separator: ",\n"))\n            )"

        return """
        // MARK: - \(machineTN) Client

        /// Dependency client for constructing \(machineTN) state machines.
        ///
        /// Inject a live implementation via `DependencyValues.\(keyName)`;
        /// swap in `.noop` or `.fromRuntime(_:)` in tests.
        @DependencyClient
        public struct \(clientN): Sendable {
            public var makeObserver: \(factoryT)

            public init(makeObserver: @escaping \(factoryT)) {
                self.makeObserver = makeObserver
            }
        }

        extension \(clientN) {
            /// No-op client whose transitions are identity operations.
            public static var noop: Self {
                Self { \(noopIgnore)\(noopCtxLine)\(noopMachine)
                }
            }

            /// Assembles a live client from explicitly provided transition closures.
            public static func fromRuntime(_ runtime: \(runtimeN)) -> Self {
                Self { \(fromRuntimeSig)\(fromRuntimeCtx)\(fromRuntimeMachine)
                }
            }
        }
        """
    }

    // MARK: - Dependency

    func emitDependencyConformance(for file: UrkelFile) -> String {
        let clientN = clientTypeName(for: file.machineName)
        let keyName = dependencyKeyName(for: file.machineName)
        return """
        // MARK: - \(typeName(from: file.machineName)) Dependency

        extension \(clientN): DependencyKey {
            public static var testValue:    Self { .noop }
            public static var previewValue: Self { .noop }
            public static var liveValue:    Self { .makeLive() }
        }

        extension DependencyValues {
            public var \(keyName): \(clientN) {
                get { self[\(clientN).self] }
                set { self[\(clientN).self] = newValue }
            }
        }
        """
    }

    // MARK: - Composed files

    private func emitStateMachineSource(for file: UrkelFile) -> String {
        var parts: [String] = [
            fileHeader(for: file),
            emitImportsBlock(for: file),
            ""
        ]
        let dataEnum = emitStateDataEnum(for: file)
        if !dataEnum.isEmpty { parts += [dataEnum, ""] }
        parts += [
            emitPhaseNamespace(for: file),
            ""
        ]
        let compoundInnerEnums = emitCompoundInnerStateEnums(for: file)
        if !compoundInnerEnums.isEmpty { parts += [compoundInnerEnums, ""] }
        parts += [
            emitMachineStruct(for: file),
            "",
            emitTransitionExtensions(for: file),
            ""
        ]
        let compoundExtensions = emitCompoundTransitionExtensions(for: file)
        if !compoundExtensions.isEmpty { parts += [compoundExtensions, ""] }
        let dataAccessors = emitStateDataAccessors(for: file)
        if !dataAccessors.isEmpty { parts += [dataAccessors, ""] }
        parts.append(emitStateEnum(for: file))
        let reactiveExt = emitReactiveExtension(for: file)
        if !reactiveExt.isEmpty { parts += ["", reactiveExt] }
        return parts.filter { !$0.isEmpty }.joined(separator: "\n")
    }

    private func emitClientSource(for file: UrkelFile) -> String {
        let parts: [String] = [
            fileHeader(for: file),
            emitImportsBlock(for: file),
            "",
            emitClientRuntime(for: file),
            "",
            emitClientStruct(for: file)
        ]
        return parts.filter { !$0.isEmpty }.joined(separator: "\n")
    }

    private func emitDependencySource(for file: UrkelFile) -> String {
        let parts: [String] = [
            fileHeader(for: file),
            emitImportsBlock(for: file),
            "",
            emitDependencyConformance(for: file)
        ]
        return parts.filter { !$0.isEmpty }.joined(separator: "\n")
    }

    // MARK: - Internal helpers

    struct TransitionClosureInfo: Hashable {
        let event: String
        let propName: String
        let params: [Parameter]

        var aliasName: String {
            let base = String(propName.dropFirst())
            return "\(typeName(from: base))Transition"
        }
        var runtimePropName: String {
            let base = aliasName.replacingOccurrences(of: "Transition", with: "")
            return variableName(from: base) + "Transition"
        }

        func closureTypeStr(ctx: String?) -> String {
            if let ctx {
                let inputs = ([ctx] + params.map(\.typeExpr)).joined(separator: ", ")
                return "@Sendable (\(inputs)) async throws -> \(ctx)"
            } else if params.isEmpty {
                return "@Sendable () async throws -> Void"
            } else {
                return "@Sendable (\(params.map(\.typeExpr).joined(separator: ", "))) async throws -> Void"
            }
        }

        static func == (lhs: Self, rhs: Self) -> Bool { lhs.propName == rhs.propName }
        func hash(into hasher: inout Hasher) { hasher.combine(propName) }
    }

    func allTransitionClosureInfos(in file: UrkelFile) -> [TransitionClosureInfo] {
        var seen = Set<String>()
        var result: [TransitionClosureInfo] = []
        let allTransitions = file.transitionStmts + compoundStates(in: file).flatMap(\.innerTransitions)
        for t in allTransitions {
            // Standard event transitions
            if case .event(let ev) = t.event, t.arrow == .standard {
                let propName = transitionPropName(for: t, in: file)
                if seen.insert(propName).inserted {
                    result.append(TransitionClosureInfo(
                        event: ev.name,
                        propName: propName,
                        params: ev.params.map { Parameter(label: $0.label, typeExpr: $0.typeExpr) }
                    ))
                }
            }
            // Timer transitions — closure takes (Ctx) -> Ctx with no event params
            if case .timer(_) = t.event, t.arrow == .standard, let dest = t.destination {
                let propName = "_timerTo\(typeName(from: dest.name))"
                if seen.insert(propName).inserted {
                    result.append(TransitionClosureInfo(
                        event: "timerTo\(typeName(from: dest.name))",
                        propName: propName,
                        params: []
                    ))
                }
            }
        }
        return result
    }

    private func transitionPropName(for t: TransitionStmt, in file: UrkelFile) -> String {
        guard case .event(let ev) = t.event, case .state(let ref) = t.source else { return "_unknown" }
        let siblings = file.transitionStmts.filter { s in
            guard case .event(let sev) = s.event, sev.name == ev.name, s.arrow == .standard else { return false }
            guard case .state(let sref) = s.source, sref.name == ref.name else { return false }
            return true
        }
        if siblings.contains(where: { $0.guard != nil }), let dest = t.destination {
            return "_\(variableName(from: typeName(from: ev.name)))To\(typeName(from: dest.name))"
        } else {
            return closurePropertyName(for: ev.name, params: ev.params.map { Parameter(label: $0.label, typeExpr: $0.typeExpr) })
        }
    }

    private func outgoing(from state: String, in file: UrkelFile) -> [TransitionStmt] {
        file.transitionStmts.filter {
            guard case .state(let ref) = $0.source else { return false }
            return ref.name == state
        }
    }

    // MARK: - State data helpers (US-5.4/5.5)

    func statesWithData(in file: UrkelFile) -> [SimpleStateDecl] {
        file.simpleStates.filter { !$0.params.isEmpty }
    }

    func stateDataEnumName(for machineName: String) -> String {
        "_\(typeName(from: machineName))StateData"
    }

    private func stateDataCaseName(for stateName: String) -> String {
        variableName(from: typeName(from: stateName))
    }

    // MARK: - Action/Guard helpers (US-5.6/5.7)

    func uniqueActionNames(in file: UrkelFile) -> [String] {
        var seen = Set<String>()
        var result: [String] = []
        for t in file.transitionStmts {
            for a in (t.action?.actions ?? []) where seen.insert(a).inserted { result.append(a) }
        }
        for hook in file.entryExitHooks {
            for a in hook.actions where seen.insert(a).inserted { result.append(a) }
        }
        for r in file.reactiveStmts {
            for a in (r.action?.actions ?? []) where seen.insert(a).inserted { result.append(a) }
        }
        return result
    }

    func uniqueGuardNames(in file: UrkelFile) -> [String] {
        var seen = Set<String>()
        var result: [String] = []
        for t in file.transitionStmts {
            if let g = t.guard {
                switch g {
                case .named(let n), .negated(let n):
                    if seen.insert(n).inserted { result.append(n) }
                case .else:
                    break
                }
            }
        }
        return result
    }

    private func entryActions(for stateName: String, in file: UrkelFile) -> [String] {
        file.entryExitHooks
            .filter { $0.hook == .entry && $0.state.name == stateName }
            .flatMap(\.actions)
    }

    private func exitActions(for stateName: String, in file: UrkelFile) -> [String] {
        file.entryExitHooks
            .filter { $0.hook == .exit && $0.state.name == stateName }
            .flatMap(\.actions)
    }

    // MARK: - Machine construction helper

    private func machineConstructionArgs(
        destStateName: String,
        file: UrkelFile,
        indent: Int = 12,
        forkedMachineName: String? = nil
    ) -> String {
        let pad    = String(repeating: " ", count: indent)
        let hasCtx = file.contextType != nil
        let sdStates = statesWithData(in: file)
        var args: [String] = []

        if hasCtx { args.append("\(pad)_context: next") }

        if !sdStates.isEmpty {
            if let destState = file.simpleStates.first(where: { $0.name == destStateName }),
               !destState.params.isEmpty {
                let cn     = stateDataCaseName(for: destStateName)
                let fields = destState.params.map { "\($0.label): \($0.label)" }.joined(separator: ", ")
                args.append("\(pad)_stateData: .\(cn)(\(fields))")
            } else {
                args.append("\(pad)_stateData: .none")
            }
        }

        for info in allTransitionClosureInfos(in: file) {
            args.append("\(pad)\(info.propName): \(info.propName)")
        }
        for name in uniqueActionNames(in: file) {
            let p = actionPropertyName(for: name)
            args.append("\(pad)\(p): \(p)")
        }
        for name in uniqueGuardNames(in: file) {
            let p = guardPropertyName(for: name)
            args.append("\(pad)\(p): \(p)")
        }
        if hasTimers(in: file) {
            args.append("\(pad)_timerTask: nil")
        }

        // Sub-machine args (US-5.11)
        for imp in subMachineImports(in: file) {
            let typN = typeName(from: imp.name)
            let varN = stateCaseName(for: imp.name)
            if forkedMachineName == imp.name {
                args.append("\(pad)_\(varN)State: \(varN)")
            } else {
                args.append("\(pad)_\(varN)State: _\(varN)State")
            }
            args.append("\(pad)_make\(typN): _make\(typN)")
        }

        // Compound inner state args (US-5.12)
        for compound in compoundStates(in: file) {
            let varN = stateCaseName(for: compound.name)
            args.append("\(pad)_\(varN)InnerState: _\(varN)InnerState")
        }

        return args.joined(separator: ",\n")
    }

    // MARK: - Timer helpers (US-5.10)

    func statesWithTimers(in file: UrkelFile) -> [SimpleStateDecl] {
        file.simpleStates.filter { state in
            file.transitionStmts.contains { t in
                guard case .timer(_) = t.event, t.arrow == .standard else { return false }
                guard case .state(let ref) = t.source else { return false }
                return ref.name == state.name
            }
        }
    }

    func hasTimers(in file: UrkelFile) -> Bool {
        !statesWithTimers(in: file).isEmpty
    }

    private func emitTimerMethods(
        transitions: [TransitionStmt],
        sourceState: String,
        file: UrkelFile
    ) -> [String] {
        let machineT = machineTypeName(for: file.machineName)
        let phaseT   = phaseNamespaceName(for: file.machineName)
        let stateT   = typeName(from: sourceState)
        let hasCtx   = file.contextType != nil
        let nextOrCtx = hasCtx ? "next" : ""
        var result: [String] = []

        // startTimer(onFire:) — one per source phase (uses first timer's duration)
        if let first = transitions.first, case .timer(let td) = first.event, let firstDest = first.destination {
            let secs    = td.duration.seconds
            let secsLit = secs == Double(Int(secs)) ? "\(Int(secs))" : "\(secs)"
            let destT   = typeName(from: firstDest.name)
            result.append("""
                /// Starts the \(secsLit)-second timer for `\(sourceState) → \(firstDest.name)`.
                /// Call immediately after entering `\(sourceState)`. The machine is consumed
                /// by the returned value — do not use `self` after calling this.
                public consuming func startTimer(
                    onFire: @escaping @Sendable (consuming \(machineT)<\(phaseT).\(stateT)>) async -> Void
                ) -> \(machineT)<\(phaseT).\(stateT)> {
                    var m = self
                    m._timerTask = Task {
                        try? await Task.sleep(for: .seconds(\(secsLit)))
                        guard !Task.isCancelled else { return }
                        await onFire(consume m)
                    }
                    return m
                }
            """)
        }

        // to<Dest>() consuming method for each timer destination
        for t in transitions {
            guard case .timer(_) = t.event, let dest = t.destination else { continue }
            let destT    = typeName(from: dest.name)
            let retT     = "\(machineT)<\(phaseT).\(destT)>"
            let propName = "_timerTo\(destT)"
            var body: [String] = []
            body.append("        _timerTask?.cancel()")
            for a in exitActions(for: sourceState, in: file) {
                body.append("        await \(actionPropertyName(for: a))(\(hasCtx ? "_context" : ""))")
            }
            if hasCtx {
                body.append("        let next = try await \(propName)(_context)")
            }
            for a in (t.action?.actions ?? []) {
                body.append("        await \(actionPropertyName(for: a))(\(nextOrCtx))")
            }
            for a in entryActions(for: dest.name, in: file) {
                body.append("        await \(actionPropertyName(for: a))(\(nextOrCtx))")
            }
            let constructArgs = machineConstructionArgs(destStateName: dest.name, file: file, indent: 12)
            body.append("        return \(retT)(\n\(constructArgs)\n        )")
            let throwsKw = hasCtx ? " async throws" : ""
            result.append("""
                /// Performs the timer-fired transition `\(sourceState) → \(dest.name)`.
                /// Called inside the `onFire` callback supplied to `startTimer(onFire:)`.
                public consuming func to\(destT)()\(throwsKw) -> \(retT) {
            \(body.joined(separator: "\n"))
                }
            """)
        }
        return result
    }

    // MARK: - Sub-machine helpers (US-5.11)

    private func subMachineImports(in file: UrkelFile) -> [ImportDecl] {
        let forkMachines = Set(file.transitionStmts.compactMap { $0.fork?.machine })
        let reactiveMachines = Set(file.reactiveStmts.compactMap { r -> String? in
            if case .machine(let n) = r.source.target { return n }
            return nil
        })
        let referenced = forkMachines.union(reactiveMachines)
        return file.imports.filter { referenced.contains($0.name) }
    }

    // MARK: - Compound state helpers (US-5.12)

    private func compoundStates(in file: UrkelFile) -> [CompoundStateDecl] {
        file.states.compactMap { guard case .compound(let c) = $0 else { return nil }; return c }
    }

    private func innerStateEnumName(for compoundName: String, machineName: String) -> String {
        "\(typeName(from: machineName))\(typeName(from: compoundName))State"
    }

    private func resolveCompoundDest(_ destName: String, in file: UrkelFile) -> String {
        if let compound = compoundStates(in: file).first(where: { $0.name == destName }) {
            let initChild = compound.children.first(where: { $0.kind == .`init` }) ?? compound.children.first
            if let child = initChild { return "\(destName).\(child.name)" }
        }
        return destName
    }

    private func phasePath(for stateName: String, in file: UrkelFile) -> String {
        let parts = stateName.components(separatedBy: ".").map { typeName(from: $0) }
        return "\(phaseNamespaceName(for: file.machineName)).\(parts.joined(separator: "."))"
    }

    private func emitCompoundInnerStateEnums(for file: UrkelFile) -> String {
        let compounds = compoundStates(in: file)
        guard !compounds.isEmpty else { return "" }
        let machineTN = typeName(from: file.machineName)
        let machineT  = machineTypeName(for: file.machineName)
        let phaseT    = phaseNamespaceName(for: file.machineName)

        return compounds.map { compound -> String in
            let enumName    = innerStateEnumName(for: compound.name, machineName: file.machineName)
            let compoundTN  = typeName(from: compound.name)
            let cases = compound.children.map { child -> String in
                let childTN  = typeName(from: child.name)
                let caseName = stateCaseName(for: child.name)
                return "    case \(caseName)(\(machineT)<\(phaseT).\(compoundTN).\(childTN)>)"
            }.joined(separator: "\n")
            return """
            // MARK: - \(machineTN) \(compoundTN) Inner State

            public enum \(enumName): ~Copyable {
            \(cases)
            }
            """
        }.joined(separator: "\n\n")
    }

    private func emitCompoundTransitionExtensions(for file: UrkelFile) -> String {
        let compounds = compoundStates(in: file)
        guard !compounds.isEmpty else { return "" }
        let machineT = machineTypeName(for: file.machineName)
        let phaseT   = phaseNamespaceName(for: file.machineName)
        let hasCtx   = file.contextType != nil

        var extensions: [String] = []

        for compound in compounds {
            let compoundTN = typeName(from: compound.name)

            for child in compound.children {
                guard child.kind != .final else { continue }
                let childTN     = typeName(from: child.name)
                let sourcePhase = "\(phaseT).\(compoundTN).\(childTN)"

                var methods: [String] = []

                // Inner transitions from this child
                for t in compound.innerTransitions {
                    guard case .state(let ref) = t.source else { continue }
                    guard ref.name == "\(compound.name).\(child.name)" || ref.name == child.name else { continue }
                    guard case .event(let ev) = t.event, t.arrow == .standard, let dest = t.destination else { continue }

                    let resolvedDest = resolveCompoundDest(dest.name, in: file)
                    let returnT      = "\(machineT)<\(phasePath(for: resolvedDest, in: file))>"
                    let propName     = transitionPropName(for: t, in: file)
                    let paramSig     = ev.params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
                    let callArgs     = ev.params.map(\.label).joined(separator: ", ")

                    var body: [String] = []
                    if hasCtx {
                        let callExpr = callArgs.isEmpty ? "_context" : "_context, \(callArgs)"
                        body.append("        let next = try await \(propName)(\(callExpr))")
                    } else if !ev.params.isEmpty {
                        body.append("        try await \(propName)(\(callArgs))")
                    }
                    let constructArgs = machineConstructionArgs(destStateName: dest.name, file: file, indent: 12)
                    body.append("        return \(returnT)(\n\(constructArgs)\n        )")

                    let throwsKw = hasCtx ? " async throws" : ""
                    methods.append("""
                        /// Transitions from `\(compound.name).\(child.name)` to `\(dest.name)`.
                        public consuming func \(ev.name)(\(paramSig))\(throwsKw) -> \(returnT) {
                    \(body.joined(separator: "\n"))
                        }
                    """)
                }

                // Outer compound transitions: from compound source to outside
                let outerTransitions = file.transitionStmts.filter { t in
                    guard case .state(let ref) = t.source else { return false }
                    return ref.name == compound.name
                }

                for t in outerTransitions {
                    guard case .event(let ev) = t.event, t.arrow == .standard, let dest = t.destination else { continue }

                    let resolvedDest = resolveCompoundDest(dest.name, in: file)
                    let returnT      = "\(machineT)<\(phasePath(for: resolvedDest, in: file))>"
                    let propName     = transitionPropName(for: t, in: file)
                    let paramSig     = ev.params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
                    let callArgs     = ev.params.map(\.label).joined(separator: ", ")

                    var body: [String] = []
                    if hasCtx {
                        let callExpr = callArgs.isEmpty ? "_context" : "_context, \(callArgs)"
                        body.append("        let next = try await \(propName)(\(callExpr))")
                    } else if !ev.params.isEmpty {
                        body.append("        try await \(propName)(\(callArgs))")
                    }
                    let constructArgs = machineConstructionArgs(destStateName: dest.name, file: file, indent: 12)
                    body.append("        return \(returnT)(\n\(constructArgs)\n        )")

                    let throwsKw = hasCtx ? " async throws" : ""
                    methods.append("""
                        /// Transitions from `\(compound.name)` to `\(dest.name)`.
                        public consuming func \(ev.name)(\(paramSig))\(throwsKw) -> \(returnT) {
                    \(body.joined(separator: "\n"))
                        }
                    """)
                }

                guard !methods.isEmpty else { continue }

                extensions.append("""
                // MARK: - \(machineT)<\(compoundTN).\(childTN)>

                extension \(machineT) where Phase == \(sourcePhase) {
                \(methods.joined(separator: "\n\n"))
                }
                """)
            }
        }

        return extensions.joined(separator: "\n\n")
    }

    private func reactiveMachineConstructionArgs(
        destStateName: String,
        file: UrkelFile,
        indent: Int = 12
    ) -> String {
        let pad      = String(repeating: " ", count: indent)
        let hasCtx   = file.contextType != nil
        let sdStates = statesWithData(in: file)
        var args: [String] = []
        if hasCtx { args.append("\(pad)_context: m._context") }
        if !sdStates.isEmpty { args.append("\(pad)_stateData: .none") }
        for info in allTransitionClosureInfos(in: file) {
            args.append("\(pad)\(info.propName): m.\(info.propName)")
        }
        for name in uniqueActionNames(in: file) {
            let p = actionPropertyName(for: name)
            args.append("\(pad)\(p): m.\(p)")
        }
        for name in uniqueGuardNames(in: file) {
            let p = guardPropertyName(for: name)
            args.append("\(pad)\(p): m.\(p)")
        }
        if hasTimers(in: file) { args.append("\(pad)_timerTask: nil") }
        for imp in subMachineImports(in: file) {
            let typN = typeName(from: imp.name)
            let varN = stateCaseName(for: imp.name)
            args.append("\(pad)_\(varN)State: m._\(varN)State")
            args.append("\(pad)_make\(typN): m._make\(typN)")
        }
        for compound in compoundStates(in: file) {
            let varN = stateCaseName(for: compound.name)
            args.append("\(pad)_\(varN)InnerState: m._\(varN)InnerState")
        }
        return args.joined(separator: ",\n")
    }

    private func emitReactiveExtension(for file: UrkelFile) -> String {
        let reactives = file.reactiveStmts
        guard !reactives.isEmpty else { return "" }

        let enumName   = stateEnumTypeName(for: file.machineName)
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let hasCtx     = file.contextType != nil

        var methods: [String] = []

        for r in reactives {
            guard case .machine(let sourceMachineName) = r.source.target else { continue }

            let reactiveStatePart: String
            switch r.source.state {
            case .named(let n): reactiveStatePart = typeName(from: n)
            case .`init`:       reactiveStatePart = "Init"
            case .final:        reactiveStatePart = "Final"
            case .any:          reactiveStatePart = "Any"
            }
            let methodName = "on\(typeName(from: sourceMachineName))\(reactiveStatePart)"

            if r.arrow == .internal {
                // Borrowing in-place handler
                var cases: [String] = []
                for stateDecl in file.states {
                    guard case .simple(let s) = stateDecl else { continue }
                    guard s.kind != .final else { continue }
                    guard r.ownState == nil || r.ownState == s.name else { continue }
                    let cn = stateCaseName(for: s.name)
                    let actionCalls = (r.action?.actions ?? []).map { a -> String in
                        "await m.\(actionPropertyName(for: a))(\(hasCtx ? "m._context" : ""))"
                    }.joined(separator: "; ")
                    cases.append("        case .\(cn)(let m): \(actionCalls)")
                }
                let switchBody = cases.isEmpty ? "        default: break" : cases.joined(separator: "\n") + "\n        default: break"
                methods.append("""
                    public borrowing func \(methodName)() async {
                        switch self {
                \(switchBody)
                        }
                    }
                """)
            } else {
                // Consuming transition
                let destName = r.destination?.name ?? ""
                let resolvedDest = resolveCompoundDest(destName, in: file)
                let returnT = enumName

                var switchCases: [String] = []
                for stateDecl in file.states {
                    switch stateDecl {
                    case .compound(let compound):
                        let cn = stateCaseName(for: compound.name)
                        switchCases.append("        case .\(cn)(let m): return .\(cn)(m)")
                    case .simple(let s):
                        let cn = stateCaseName(for: s.name)
                        let shouldTransition = (r.ownState == nil || r.ownState == s.name) && s.kind != .final
                        if shouldTransition && !destName.isEmpty {
                            let destCaseName = stateCaseName(for: resolvedDest.components(separatedBy: ".").last ?? resolvedDest)
                            let constructArgs = reactiveMachineConstructionArgs(destStateName: destName, file: file, indent: 16)
                            // Check if dest is compound - wrap in inner enum
                            if let compound = compoundStates(in: file).first(where: { $0.name == destName }) {
                                let innerEnumN = innerStateEnumName(for: compound.name, machineName: file.machineName)
                                let initChild = compound.children.first(where: { $0.kind == .`init` }) ?? compound.children.first
                                if let child = initChild {
                                    let childCaseName = stateCaseName(for: child.name)
                                    let resolvedPhase = phasePath(for: "\(destName).\(child.name)", in: file)
                                    let machineExpr = "\(machineT)<\(resolvedPhase)>(\n\(constructArgs)\n            )"
                                    switchCases.append("        case .\(cn)(let m): return .\(stateCaseName(for: destName))(\(innerEnumN).\(childCaseName)(\(machineExpr)))")
                                } else {
                                    switchCases.append("        case .\(cn)(let m): return .\(cn)(m)")
                                }
                            } else {
                                let destPhase = phasePath(for: resolvedDest, in: file)
                                let machineExpr = "\(machineT)<\(destPhase)>(\n\(constructArgs)\n            )"
                                switchCases.append("        case .\(cn)(let m): return .\(destCaseName)(\(machineExpr))")
                            }
                        } else {
                            switchCases.append("        case .\(cn)(let m): return .\(cn)(m)")
                        }
                    }
                }

                let throwsKw = hasCtx ? " async throws" : " async"
                methods.append("""
                    public consuming func \(methodName)()\(throwsKw) -> \(returnT) {
                        switch consume self {
                \(switchCases.joined(separator: "\n"))
                        }
                    }
                """)
            }
        }

        guard !methods.isEmpty else { return "" }

        return """
        extension \(enumName) {
        \(methods.joined(separator: "\n\n"))
        }
        """
    }
}

// MARK: - Errors

public enum SwiftSyntaxEmitterError: Error, LocalizedError, Sendable {
    case syntaxError(String)

    public var errorDescription: String? {
        switch self {
        case .syntaxError(let msg): return "Generated Swift has syntax errors:\n\(msg)"
        }
    }
}

// MARK: - Backward-compatible alias

/// v2 alias. Use `SwiftSyntaxEmitter` directly in new code.
public typealias UrkelV2Emitter = SwiftSyntaxEmitter
