import Foundation
import SwiftParser
import SwiftSyntax

// MARK: - SwiftSyntaxEmitter

/// The primary Urkel v2 Swift code emitter.
///
/// Generates Swift source by composing structured string segments, then
/// validates every output file by parsing it with `SwiftParser`. Any
/// syntactically invalid output is caught before it reaches disk — the
/// parse tree is the correctness proof.
///
/// The emitter is intentionally incremental: each `emit*` helper returns a
/// `String` fragment, making them independently testable and easy to
/// extend one story at a time.
///
/// Usage:
/// ```swift
/// let files = try SwiftSyntaxEmitter().emit(file: urkelFile)
/// try files.stateMachine.write(to: url, atomically: true, encoding: .utf8)
/// ```
public struct SwiftSyntaxEmitter {
    public init() {}

    // MARK: - Public API

    /// Emits three source files for the given machine and validates each one
    /// by parsing it with `SwiftParser`.
    public func emit(file: UrkelFile) throws -> EmittedFiles {
        let sm  = emitStateMachineSource(for: file)
        let cl  = emitClientSource(for: file)
        let dep = emitDependencySource(for: file)
        try [sm, cl, dep].forEach { try validate(source: $0) }
        return EmittedFiles(stateMachine: sm, client: cl, dependency: dep)
    }

    // MARK: - Validation

    /// Parses `source` with `SwiftParser` and throws if any error nodes
    /// are present — guaranteeing syntactic correctness before the file is written.
    public func validate(source: String) throws {
        let tree = Parser.parse(source: source)
        guard !tree.hasError else {
            throw SwiftSyntaxEmitterError.syntaxError("Generated source has syntax errors")
        }
    }

    // MARK: - File header

    private func fileHeader(for file: UrkelFile) -> String {
        let name = variableName(from: typeName(from: file.machineName))
        return "// Generated by Urkel — do not edit.\n// Source: \(name).urkel\n"
    }

    // MARK: - Imports

    private func emitImportsBlock(for file: UrkelFile) -> String {
        // Dependencies is always required; Foundation is standard.
        ["Dependencies", "Foundation"]
            .map { "import \($0)" }
            .joined(separator: "\n")
    }

    // MARK: - Phase Namespace

    func emitPhaseNamespace(for file: UrkelFile) -> String {
        let machineTN = typeName(from: file.machineName)
        let ns        = phaseNamespaceName(for: file.machineName)
        let cases = file.simpleStates.map { state -> String in
            let tn   = typeName(from: state.name)
            let doc  = phaseDoc(for: state.kind)
            let decl = "    \(doc)public enum \(tn) {}"
            return decl
        }.joined(separator: "\n")
        return """
        // MARK: - \(machineTN) Phases

        /// Phase markers for \(machineTN)Machine.
        /// Use `\(ns).Xxx` as the phantom `Phase` type argument.
        public enum \(ns) {
        \(cases)
        }
        """
    }

    private func phaseDoc(for kind: StateKind) -> String {
        switch kind {
        case .`init`:  return "/// The initial phase.\n    "
        case .final:   return "/// A terminal phase — no further transitions.\n    "
        case .state:   return ""
        }
    }

    // MARK: - Machine Struct

    func emitMachineStruct(for file: UrkelFile) -> String {
        let machineTN   = typeName(from: file.machineName)
        let structName  = machineTypeName(for: file.machineName)
        let hasContext  = file.contextType != nil
        let contextType = file.contextType ?? "Void"
        let sigs        = uniqueTransitionSignatures(in: file)

        var lines: [String] = []
        lines.append("// MARK: - \(machineTN) State Machine")
        lines.append("")
        lines.append("""
        /// A type-safe, move-only \(machineTN) state machine.
        ///
        /// The current phase is encoded in the `Phase` phantom type parameter.
        /// Transition methods are only available in the matching phase —
        /// invalid transitions are compile-time errors.
        public struct \(structName)<Phase>: ~Copyable, Sendable {
        """)

        if hasContext {
            lines.append("    fileprivate let _context: \(contextType)")
        }
        for sig in sigs {
            lines.append("    fileprivate let \(sig.propName): \(closureType(sig: sig, ctx: hasContext ? contextType : nil))")
        }

        // init
        var initParts: [String] = []
        if hasContext { initParts.append("        _context: \(contextType)") }
        initParts += sigs.map { "        \($0.propName): @escaping \(closureType(sig: $0, ctx: hasContext ? contextType : nil))" }
        lines.append("")
        lines.append("    internal init(")
        lines.append(initParts.joined(separator: ",\n"))
        lines.append("    ) {")
        if hasContext { lines.append("        self._context = _context") }
        for sig in sigs { lines.append("        self.\(sig.propName) = \(sig.propName)") }
        lines.append("    }")

        // withContext
        if hasContext {
            lines.append("")
            lines.append("""
                /// Read-only access to the context without consuming the machine.
                public borrowing func withContext<R>(
                    _ body: (borrowing \(contextType)) throws -> R
                ) rethrows -> R {
                    try body(_context)
                }
            """)
        }

        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Transition Extensions

    func emitTransitionExtensions(for file: UrkelFile) -> String {
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let hasContext = file.contextType != nil
        let ctx        = file.contextType ?? "Void"
        let allSigs    = uniqueTransitionSignatures(in: file)

        return file.simpleStates.compactMap { state -> String? in
            guard state.kind != .final else { return nil }
            let outgoing = outgoing(from: state.name, in: file)
            guard !outgoing.isEmpty else { return nil }

            let stateT = typeName(from: state.name)
            let header = """
            // MARK: - \(machineT)<\(stateT)>

            extension \(machineT) where Phase == \(phaseT).\(stateT) {
            """

            let methods = outgoing.compactMap { t -> String? in
                guard case .event(let ev) = t.event,
                      let dest = t.destination,
                      t.arrow == .standard else { return nil }
                let destT    = typeName(from: dest.name)
                let returnT  = "\(machineT)<\(phaseT).\(destT)>"
                let paramSig = ev.params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
                let callArgs = ev.params.map { $0.label }.joined(separator: ", ")
                let prop     = closurePropertyName(for: ev.name, params: ev.params.map { Parameter(label: $0.label, typeExpr: $0.typeExpr) })

                let doc = t.docComments.isEmpty
                    ? "    /// Transitions from `\(state.name)` to `\(dest.name)`."
                    : t.docComments.map { "    /// \($0.text)" }.joined(separator: "\n")

                let forwards = allSigs
                    .map { "            \($0.propName): \($0.propName)" }
                    .joined(separator: ",\n")

                if hasContext {
                    let callExpr = callArgs.isEmpty ? "_context" : "_context, \(callArgs)"
                    let ctxLine  = "let next = try await \(prop)(\(callExpr))"
                    let ctxInit  = forwards.isEmpty
                        ? "            _context: next"
                        : "            _context: next,\n\(forwards)"
                    return """
                    \(doc)
                        public consuming func \(ev.name)(\(paramSig)) async throws -> \(returnT) {
                            \(ctxLine)
                            return \(returnT)(
                    \(ctxInit)
                            )
                        }
                    """
                } else {
                    let ctxInit = forwards.isEmpty ? "" : "\n\(forwards)\n        "
                    return """
                    \(doc)
                        public consuming func \(ev.name)(\(paramSig)) -> \(returnT) {
                            \(returnT)(\(ctxInit))
                        }
                    """
                }
            }.joined(separator: "\n\n")

            guard !methods.isEmpty else { return nil }
            return [header, methods, "}"].joined(separator: "\n")
        }.joined(separator: "\n\n")
    }

    // MARK: - Combined State Enum

    func emitStateEnum(for file: UrkelFile) -> String {
        let machineTN  = typeName(from: file.machineName)
        let enumName   = stateEnumTypeName(for: file.machineName)
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let hasContext = file.contextType != nil

        let cases = file.simpleStates.map { s in
            let tn = typeName(from: s.name)
            let c  = stateCaseName(for: s.name)
            return "    case \(c)(\(machineT)<\(phaseT).\(tn)>)"
        }.joined(separator: "\n")

        let initDecl: String = {
            guard let init_ = file.initState else { return "" }
            let tn = typeName(from: init_.name)
            let c  = stateCaseName(for: init_.name)
            return """

                /// Wraps an initial-phase machine.
                public init(_ initial: consuming \(machineT)<\(phaseT).\(tn)>) {
                    self = .\(c)(initial)
                }
            """
        }()

        let enumDecl = """
        // MARK: - \(machineTN) Combined State

        /// Runtime-erasure wrapper over all \(machineTN) phases.
        /// Use when the current phase is not statically known.
        public enum \(enumName): ~Copyable {
        \(cases)\(initDecl)
        }
        """

        // Accessors + delegating transitions
        let accessors = file.simpleStates.map { s -> String in
            let tn   = typeName(from: s.name)
            let c    = stateCaseName(for: s.name)
            let mt   = "\(machineT)<\(phaseT).\(tn)>"
            return """
                public borrowing func with\(tn)<R>(
                    _ body: (borrowing \(mt)) throws -> R
                ) rethrows -> R? {
                    guard case .\(c)(let m) = self else { return nil }
                    return try body(m)
                }
            """
        }.joined(separator: "\n\n")

        let delegatingMethods = uniqueTransitionSignatures(in: file).map { sig -> String in
            let paramSig  = sig.params.map { "\($0.label): \($0.typeExpr)" }.joined(separator: ", ")
            let callArgs  = sig.params.map { "\($0.label): \($0.label)" }.joined(separator: ", ")
            let switchCases = file.simpleStates.map { s -> String in
                let c_ = stateCaseName(for: s.name)
                let t  = outgoing(from: s.name, in: file).first { t in
                    guard case .event(let ev) = t.event else { return false }
                    return ev.name == sig.event && t.arrow == .standard
                }
                if let t, let dest = t.destination {
                    let dc   = stateCaseName(for: dest.name)
                    let call = callArgs.isEmpty
                        ? "try await m.\(sig.event)()"
                        : "try await m.\(sig.event)(\(callArgs))"
                    return "        case .\(c_)(let m): return .\(dc)(\(call))"
                } else {
                    return "        case .\(c_)(let m): return .\(c_)(m)"
                }
            }.joined(separator: "\n")

            if hasContext {
                return """
                    /// Attempts `\(sig.event)` from the current state. No-ops in states where it is not defined.
                    public consuming func \(sig.event)(\(paramSig)) async throws -> \(enumName) {
                        switch consume self {
                \(switchCases)
                        }
                    }
                """
            } else {
                return """
                    public consuming func \(sig.event)(\(paramSig)) -> \(enumName) {
                        switch consume self {
                \(switchCases)
                        }
                    }
                """
            }
        }.joined(separator: "\n\n")

        let ext = """
        extension \(enumName) {

        \(accessors)

        \(delegatingMethods)
        }
        """

        return [enumDecl, ext].joined(separator: "\n\n")
    }

    // MARK: - Client Runtime

    func emitClientRuntime(for file: UrkelFile) -> String {
        let runtimeN    = runtimeTypeName(for: file.machineName)
        let machineTN   = typeName(from: file.machineName)
        let hasContext   = file.contextType != nil
        let ctx          = file.contextType ?? "Void"
        let sigs         = uniqueTransitionSignatures(in: file)
        let initParams   = file.initState?.params ?? []

        var lines: [String] = ["// MARK: - \(machineTN) Runtime Builder", ""]
        lines.append("/// Provides individual transition hooks for constructing a \(machineTN)Client.")
        lines.append("public struct \(runtimeN): Sendable {")

        if hasContext {
            let pTypes = initParams.map(\.typeExpr).joined(separator: ", ")
            let initType = pTypes.isEmpty
                ? "@Sendable () -> \(ctx)"
                : "@Sendable (\(pTypes)) -> \(ctx)"
            lines.append("    public typealias InitialContextBuilder = \(initType)")
        }
        for sig in sigs {
            lines.append("    public typealias \(sig.aliasName) = \(closureType(sig: sig, ctx: hasContext ? ctx : nil))")
        }
        if hasContext { lines.append("    public let initialContext: InitialContextBuilder") }
        for sig in sigs { lines.append("    public let \(sig.runtimePropName): \(sig.aliasName)") }

        // init
        var initArgs: [String] = []
        if hasContext { initArgs.append("        initialContext: @escaping InitialContextBuilder") }
        initArgs += sigs.map { "        \($0.runtimePropName): @escaping \($0.aliasName)" }
        lines.append("")
        lines.append("    public init(")
        lines.append(initArgs.joined(separator: ",\n"))
        lines.append("    ) {")
        if hasContext { lines.append("        self.initialContext = initialContext") }
        for sig in sigs { lines.append("        self.\(sig.runtimePropName) = \(sig.runtimePropName)") }
        lines.append("    }")
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Client Struct + Extension

    func emitClientStruct(for file: UrkelFile) -> String {
        let clientN    = clientTypeName(for: file.machineName)
        let machineTN  = typeName(from: file.machineName)
        let machineT   = machineTypeName(for: file.machineName)
        let phaseT     = phaseNamespaceName(for: file.machineName)
        let runtimeN   = runtimeTypeName(for: file.machineName)
        let initState  = file.initState?.name ?? "Initial"
        let initTN     = typeName(from: initState)
        let hasContext = file.contextType != nil
        let ctx        = file.contextType ?? "Void"
        let initParams = file.initState?.params ?? []
        let sigs       = uniqueTransitionSignatures(in: file)
        let keyName    = dependencyKeyName(for: file.machineName)

        let pTypes  = initParams.map(\.typeExpr).joined(separator: ", ")
        let retT    = "\(machineT)<\(phaseT).\(initTN)>"
        let factoryT: String
        if pTypes.isEmpty {
            factoryT = "@Sendable () -> \(retT)"
        } else {
            factoryT = "@Sendable (\(pTypes)) -> \(retT)"
        }

        // noop machine construction
        let noopForwards = sigs.map { sig -> String in
            if hasContext {
                let count = sig.params.count
                let ignores = count == 0 ? "ctx, _ in ctx" : "ctx, " + (0..<count).map { _ in "_" }.joined(separator: ", ") + " in ctx"
                return "            \(sig.propName): { \(ignores) }"
            } else {
                return "            \(sig.propName): { }"
            }
        }.joined(separator: ",\n")
        let noopIgnore = initParams.isEmpty ? "" : "_ in\n            "
        let noopCtxLine = hasContext ? "let _ctx = \(ctx)()\n            " : ""
        let noopCtxArg  = hasContext ? "            _context: _ctx,\n" : ""
        let noopMachine: String
        if noopForwards.isEmpty {
            noopMachine = hasContext
                ? "\(retT)(\n            _context: _ctx\n        )"
                : "\(retT)()"
        } else {
            noopMachine = "\(retT)(\n\(noopCtxArg)\(noopForwards)\n        )"
        }

        // fromRuntime
        let fromRuntimePNames = initParams.map(\.label).joined(separator: ", ")
        let fromRuntimeSig = fromRuntimePNames.isEmpty ? "" : "\(fromRuntimePNames) in\n            "
        let fromRuntimeCtx = hasContext ? "let context = runtime.initialContext(\(fromRuntimePNames))\n            " : ""
        let fromRuntimeForwards = sigs.map { "                \($0.propName): runtime.\($0.runtimePropName)" }.joined(separator: ",\n")
        let fromRuntimeCtxArg = hasContext ? "                _context: context,\n" : ""
        let fromRuntimeMachine: String
        if fromRuntimeForwards.isEmpty {
            fromRuntimeMachine = hasContext
                ? "\(retT)(\n                _context: context\n            )"
                : "\(retT)()"
        } else {
            fromRuntimeMachine = "\(retT)(\n\(fromRuntimeCtxArg)\(fromRuntimeForwards)\n            )"
        }

        return """
        // MARK: - \(machineTN) Client

        /// Dependency client for constructing \(machineTN) state machines.
        ///
        /// Inject a live implementation via `DependencyValues.\(keyName)`;
        /// swap in `.noop` or `.fromRuntime(_:)` in tests.
        @DependencyClient
        public struct \(clientN): Sendable {
            public var makeObserver: \(factoryT)

            public init(makeObserver: @escaping \(factoryT)) {
                self.makeObserver = makeObserver
            }
        }

        extension \(clientN) {
            /// No-op client whose transitions are identity operations.
            /// Safe for previews and unit tests that do not exercise real effects.
            public static var noop: Self {
                Self { \(noopIgnore)\(noopCtxLine)\(noopMachine)
                }
            }

            /// Assembles a live client from explicitly provided transition closures.
            public static func fromRuntime(_ runtime: \(runtimeN)) -> Self {
                Self { \(fromRuntimeSig)\(fromRuntimeCtx)\(fromRuntimeMachine)
                }
            }
        }
        """
    }

    // MARK: - Dependency

    func emitDependencyConformance(for file: UrkelFile) -> String {
        let clientN = clientTypeName(for: file.machineName)
        let keyName = dependencyKeyName(for: file.machineName)
        return """
        // MARK: - \(typeName(from: file.machineName)) Dependency

        extension \(clientN): DependencyKey {
            public static var testValue:    Self { .noop }
            public static var previewValue: Self { .noop }
            public static var liveValue:    Self { .makeLive() }
        }

        extension DependencyValues {
            public var \(keyName): \(clientN) {
                get { self[\(clientN).self] }
                set { self[\(clientN).self] = newValue }
            }
        }
        """
    }

    // MARK: - Composed files

    private func emitStateMachineSource(for file: UrkelFile) -> String {
        let parts: [String] = [
            fileHeader(for: file),
            emitImportsBlock(for: file),
            "",
            emitPhaseNamespace(for: file),
            "",
            emitMachineStruct(for: file),
            "",
            emitTransitionExtensions(for: file),
            "",
            emitStateEnum(for: file)
        ]
        return parts.filter { !$0.isEmpty }.joined(separator: "\n")
    }

    private func emitClientSource(for file: UrkelFile) -> String {
        let parts: [String] = [
            fileHeader(for: file),
            emitImportsBlock(for: file),
            "",
            emitClientRuntime(for: file),
            "",
            emitClientStruct(for: file)
        ]
        return parts.filter { !$0.isEmpty }.joined(separator: "\n")
    }

    private func emitDependencySource(for file: UrkelFile) -> String {
        let parts: [String] = [
            fileHeader(for: file),
            emitImportsBlock(for: file),
            "",
            emitDependencyConformance(for: file)
        ]
        return parts.filter { !$0.isEmpty }.joined(separator: "\n")
    }

    // MARK: - Internal helpers

    private struct TransitionSignature: Hashable {
        let event: String
        let params: [Parameter]

        var propName: String { closurePropertyName(for: event, params: params) }
        var aliasName: String {
            let base   = typeName(from: event)
            let suffix = params.map { typeName(from: $0.typeExpr.components(separatedBy: .init(charactersIn: ":<>[]?,")).first ?? $0.typeExpr) }.joined()
            return "\(base)\(suffix)Transition"
        }
        var runtimePropName: String {
            let base = aliasName.replacingOccurrences(of: "Transition", with: "")
            return variableName(from: base) + "Transition"
        }

        static func == (lhs: Self, rhs: Self) -> Bool {
            lhs.event == rhs.event &&
            lhs.params.map { "\($0.label):\($0.typeExpr)" } ==
            rhs.params.map { "\($0.label):\($0.typeExpr)" }
        }
        func hash(into hasher: inout Hasher) {
            hasher.combine(event)
            hasher.combine(params.map { "\($0.label):\($0.typeExpr)" })
        }
    }

    private func uniqueTransitionSignatures(in file: UrkelFile) -> [TransitionSignature] {
        var seen = Set<TransitionSignature>()
        var ordered: [TransitionSignature] = []
        for t in file.transitionStmts {
            guard case .event(let ev) = t.event, t.arrow == .standard else { continue }
            let sig = TransitionSignature(
                event: ev.name,
                params: ev.params.map { Parameter(label: $0.label, typeExpr: $0.typeExpr) }
            )
            if seen.insert(sig).inserted { ordered.append(sig) }
        }
        return ordered
    }

    private func outgoing(from state: String, in file: UrkelFile) -> [TransitionStmt] {
        file.transitionStmts.filter {
            guard case .state(let ref) = $0.source else { return false }
            return ref.name == state
        }
    }

    private func closureType(sig: TransitionSignature, ctx: String?) -> String {
        if let ctx {
            let inputs = ([ctx] + sig.params.map(\.typeExpr)).joined(separator: ", ")
            return "@Sendable (\(inputs)) async throws -> \(ctx)"
        } else if sig.params.isEmpty {
            return "@Sendable () async throws -> Void"
        } else {
            return "@Sendable (\(sig.params.map(\.typeExpr).joined(separator: ", "))) async throws -> Void"
        }
    }
}

// MARK: - Errors

public enum SwiftSyntaxEmitterError: Error, LocalizedError, Sendable {
    case syntaxError(String)

    public var errorDescription: String? {
        switch self {
        case .syntaxError(let msg): return "Generated Swift has syntax errors:\n\(msg)"
        }
    }
}

// MARK: - Backward-compatible alias

/// v2 alias. Use `SwiftSyntaxEmitter` directly in new code.
public typealias UrkelV2Emitter = SwiftSyntaxEmitter
