import Testing
import Foundation
@testable import Urkel
@testable import UrkelAST
@testable import UrkelParser
@testable import UrkelEmitterSwift

// MARK: - Fixtures

/// A minimal machine with context, two phases, and one transition each.
func makeFolderWatchFile() -> UrkelFile {
    UrkelFile(
        machineName: "FolderWatch",
        contextType: "FolderContext",
        imports: [ImportDecl(name: "Foundation")],
        states: [
            .simple(SimpleStateDecl(kind: .`init`, name: "Idle")),
            .simple(SimpleStateDecl(kind: .state, name: "Running")),
            .simple(SimpleStateDecl(kind: .final, name: "Stopped")),
        ],
        transitions: [
            .transition(TransitionStmt(
                source: .state(StateRef("Idle")),
                event: .event(EventDecl(name: "start")),
                destination: StateRef("Running")
            )),
            .transition(TransitionStmt(
                source: .state(StateRef("Running")),
                event: .event(EventDecl(name: "stop")),
                destination: StateRef("Stopped")
            )),
        ]
    )
}

/// A minimal machine without a context type.
func makeToggleFile() -> UrkelFile {
    UrkelFile(
        machineName: "Toggle",
        states: [
            .simple(SimpleStateDecl(kind: .`init`, name: "Off")),
            .simple(SimpleStateDecl(kind: .state, name: "On")),
            .simple(SimpleStateDecl(kind: .final, name: "Destroyed")),
        ],
        transitions: [
            .transition(TransitionStmt(source: .state(StateRef("Off")), event: .event(EventDecl(name: "toggle")), destination: StateRef("On"))),
            .transition(TransitionStmt(source: .state(StateRef("On")),  event: .event(EventDecl(name: "toggle")), destination: StateRef("Off"))),
            .transition(TransitionStmt(source: .state(StateRef("Off")), event: .event(EventDecl(name: "destroy")), destination: StateRef("Destroyed"))),
            .transition(TransitionStmt(source: .state(StateRef("On")),  event: .event(EventDecl(name: "destroy")), destination: StateRef("Destroyed"))),
        ]
    )
}

// MARK: - Infrastructure tests

@Suite("US-5.1 — Emitter Infrastructure")
struct EmitterInfrastructureTests {

    @Test("emit returns non-empty EmittedFiles")
    func emitReturnsNonEmpty() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(!files.stateMachine.isEmpty)
        #expect(!files.client.isEmpty)
        #expect(!files.dependency.isEmpty)
    }

    @Test("every emitted file starts with the generated header")
    func fileHeaders() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        for field in [files.stateMachine, files.client, files.dependency] {
            #expect(field.hasPrefix("// Generated by Urkel"))
        }
    }

    @Test("stateMachine file parses without errors")
    func stateMachineParses() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        try SwiftSyntaxEmitter().validate(source: files.stateMachine)
    }

    @Test("client file parses without errors")
    func clientParses() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        try SwiftSyntaxEmitter().validate(source: files.client)
    }

    @Test("dependency file parses without errors")
    func dependencyParses() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        try SwiftSyntaxEmitter().validate(source: files.dependency)
    }

    @Test("MustacheEmitter renders a trivial template")
    func mustacheSimpleTemplate() throws {
        let result = try MustacheEmitter().render(
            file: makeFolderWatchFile(),
            templateString: "{{machineName}}"
        )
        #expect(result == "FolderWatch")
    }

    @Test("MustacheEmitter throws on invalid template")
    func mustacheInvalidTemplate() {
        #expect(throws: MustacheEmitterError.self) {
            try MustacheEmitter().render(
                file: makeFolderWatchFile(),
                templateString: "{{#unclosed"
            )
        }
    }
}

// MARK: - Core machine emission tests

@Suite("US-5.2 — Core Machine Emission")
struct CoreMachineEmissionTests {

    @Test("phase namespace is emitted")
    func phaseNamespace() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.stateMachine.contains("public enum FolderWatchPhase"))
        #expect(files.stateMachine.contains("public enum Idle {}"))
        #expect(files.stateMachine.contains("public enum Running {}"))
        #expect(files.stateMachine.contains("public enum Stopped {}"))
    }

    @Test("machine struct is ~Copyable and Sendable")
    func machineStructConformances() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.stateMachine.contains("public struct FolderWatchMachine<Phase>: ~Copyable, Sendable"))
    }

    @Test("transition extension uses consuming func with specific return type")
    func consumingFuncReturnType() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.stateMachine.contains(
            "public consuming func start() async throws -> FolderWatchMachine<FolderWatchPhase.Running>"
        ))
        #expect(files.stateMachine.contains(
            "public consuming func stop() async throws -> FolderWatchMachine<FolderWatchPhase.Stopped>"
        ))
    }

    @Test("combined state enum with ~Copyable")
    func combinedStateEnum() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.stateMachine.contains("public enum FolderWatchState: ~Copyable"))
        #expect(files.stateMachine.contains("case idle(FolderWatchMachine<FolderWatchPhase.Idle>)"))
        #expect(files.stateMachine.contains("case running(FolderWatchMachine<FolderWatchPhase.Running>)"))
        #expect(files.stateMachine.contains("case stopped(FolderWatchMachine<FolderWatchPhase.Stopped>)"))
    }

    @Test("state enum has init for initial phase")
    func stateEnumInit() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.stateMachine.contains("public init(_ initial: consuming FolderWatchMachine<FolderWatchPhase.Idle>)"))
    }

    @Test("state enum has borrowing withXxx accessors")
    func borrowingAccessors() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.stateMachine.contains("public borrowing func withIdle<R>"))
        #expect(files.stateMachine.contains("public borrowing func withRunning<R>"))
        #expect(files.stateMachine.contains("public borrowing func withStopped<R>"))
    }

    @Test("machine without context has no context closure")
    func noContextMachine() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeToggleFile())
        #expect(!files.stateMachine.contains("fileprivate let _context"))
        #expect(!files.stateMachine.contains("FolderContext"))
    }

    @Test("all emitted files parse without errors (Toggle)")
    func toggleFilesParseClean() throws {
        let emitter = SwiftSyntaxEmitter()
        let files = try emitter.emit(file: makeToggleFile())
        try [files.stateMachine, files.client, files.dependency]
            .forEach { try emitter.validate(source: $0) }
    }
}

// MARK: - Client & Dependency tests

@Suite("US-5.3 — Client & Dependency Emission")
struct ClientDependencyEmissionTests {

    @Test("runtime builder struct is emitted")
    func runtimeBuilderEmitted() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.client.contains("public struct FolderWatchClientRuntime: Sendable"))
        #expect(files.client.contains("typealias StartTransition"))
        #expect(files.client.contains("typealias StopTransition"))
    }

    @Test("client struct has @DependencyClient and makeObserver")
    func clientStructEmitted() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.client.contains("@DependencyClient"))
        #expect(files.client.contains("public struct FolderWatchClient: Sendable"))
        #expect(files.client.contains("public var makeObserver"))
    }

    @Test("noop client is emitted")
    func noopEmitted() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.client.contains("public static var noop: Self"))
    }

    @Test("fromRuntime is emitted")
    func fromRuntimeEmitted() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.client.contains("public static func fromRuntime(_ runtime: FolderWatchClientRuntime) -> Self"))
    }

    @Test("dependency conformance and DependencyValues extension are emitted")
    func dependencyConformanceEmitted() throws {
        let files = try SwiftSyntaxEmitter().emit(file: makeFolderWatchFile())
        #expect(files.dependency.contains("extension FolderWatchClient: DependencyKey"))
        #expect(files.dependency.contains("extension DependencyValues"))
        #expect(files.dependency.contains("var folderWatch: FolderWatchClient"))
    }

    @Test("MustacheEmitter templateContext has correct keys")
    func mustacheTemplateContext() throws {
        let file = makeFolderWatchFile()
        let ctx  = file.templateContext
        #expect((ctx["machineName"] as? String) == "FolderWatch")
        #expect((ctx["machineTypeName"] as? String) == "FolderWatch")
        #expect((ctx["hasContext"] as? Bool) == true)
        let states = ctx["states"] as? [[String: Any]]
        #expect(states?.count == 3)
    }
}
