import UrkelAST
import UrkelParser
import UrkelValidation
import UrkelEmitterSwift
import UrkelEmitterMustache
import Foundation

public enum UrkelGeneratorError: Error, LocalizedError {
    case fileNotFound(String)
    case notAFile(String)
    case unsupportedLanguage(String)
    case languageTemplateMissing(String)
    case invalidConfiguration(URL, details: String)

    public var errorDescription: String? {
        switch self {
        case .fileNotFound(let path):
            return "Error: File not found at path: \(path)"
        case .notAFile(let path):
            return "Error: Path is not a readable file: \(path)"
        case .unsupportedLanguage(let language):
            return "Unsupported language: \(language)"
        case .languageTemplateMissing(let language):
            return "Bundled template for language '\(language)' was not found."
        case .invalidConfiguration(let url, let details):
            return "Invalid Urkel configuration at \(url.path): \(details)"
        }
    }
}

public struct UrkelGenerator {
    public init() {}

    @discardableResult
    public func generatePlaceholder(inputPath: String, outputPath: String) throws -> URL {
        let inputURL = URL(fileURLWithPath: inputPath)
        guard FileManager.default.fileExists(atPath: inputURL.path) else {
            throw UrkelGeneratorError.fileNotFound(inputURL.path)
        }

        var isDirectory = ObjCBool(false)
        guard FileManager.default.fileExists(atPath: inputURL.path, isDirectory: &isDirectory), !isDirectory.boolValue else {
            throw UrkelGeneratorError.notAFile(inputURL.path)
        }

        _ = try String(contentsOf: inputURL, encoding: .utf8)

        let outputURL = URL(fileURLWithPath: outputPath, isDirectory: true)
        try FileManager.default.createDirectory(at: outputURL, withIntermediateDirectories: true)

        let baseName = inputURL.deletingPathExtension().lastPathComponent
        let generatedURL = outputURL.appendingPathComponent("\(baseName)+Generated.swift")
        try "// Placeholder generated by Urkel\n".write(to: generatedURL, atomically: true, encoding: .utf8)
        return generatedURL
    }

    @discardableResult
    public func generate(
        inputPath: String,
        outputPath: String,
        templatePath: String? = nil,
        outputExtension: String? = nil,
        language: String? = nil,
        swiftImports: [String]? = nil,
        templateImports: [String]? = nil,
        additionalConfigSearchDirectories: [URL] = [],
        verboseConfiguration: Bool = false,
        composedASTs: [String: UrkelFile] = [:]
    ) throws -> [URL] {
        let inputURL = URL(fileURLWithPath: inputPath)
        guard FileManager.default.fileExists(atPath: inputURL.path) else {
            throw UrkelGeneratorError.fileNotFound(inputURL.path)
        }

        var isDirectory = ObjCBool(false)
        guard FileManager.default.fileExists(atPath: inputURL.path, isDirectory: &isDirectory), !isDirectory.boolValue else {
            throw UrkelGeneratorError.notAFile(inputURL.path)
        }

        let source = try String(contentsOf: inputURL, encoding: .utf8)
        let fallbackName = inputURL.deletingPathExtension().lastPathComponent

        let resolvedConfiguration: UrkelResolvedConfiguration
        do {
            resolvedConfiguration = try UrkelConfigurationResolver.resolveGenerationConfiguration(
                for: inputURL,
                overrides: UrkelGenerationOverrides(
                    templatePath: templatePath,
                    outputExtension: outputExtension,
                    language: language,
                    swiftImports: swiftImports,
                    templateImports: templateImports
                ),
                additionalSearchDirectories: additionalConfigSearchDirectories
            )
        } catch let error as UrkelConfigurationError {
            switch error {
            case .invalidConfiguration(let url, let underlying):
                throw UrkelGeneratorError.invalidConfiguration(url, details: underlying.localizedDescription)
            }
        }

        // Parse with v2 parser
        var file = try UrkelParser().parse(source: source, machineNameFallback: fallbackName)

        // If machine name defaulted to "Machine", use the file name
        if file.machineName == "Machine" {
            file = UrkelFile(
                machineName: fallbackName,
                contextType: file.contextType,
                docComments: file.docComments,
                imports: file.imports,
                parallels: file.parallels,
                states: file.states,
                entryExitHooks: file.entryExitHooks,
                transitions: file.transitions,
                invariants: file.invariants
            )
        }

        // Merge config swift imports into the file's import list
        if let configImports = resolvedConfiguration.swiftImports, !configImports.isEmpty {
            let existing = Set(file.imports.map(\.name))
            let extra = configImports
                .filter { !existing.contains($0) }
                .map { ImportDecl(name: $0) }
            file = UrkelFile(
                machineName: file.machineName,
                contextType: file.contextType,
                docComments: file.docComments,
                imports: file.imports + extra,
                parallels: file.parallels,
                states: file.states,
                entryExitHooks: file.entryExitHooks,
                transitions: file.transitions,
                invariants: file.invariants
            )
        }

        // Validate with v2 validator
        try UrkelValidator.validateThrowing(file)

        let outputRootURL = URL(fileURLWithPath: outputPath, isDirectory: true)
        let outputURL = Self.resolvedOutputDirectoryURL(
            from: outputRootURL,
            configuredOutputFolder: resolvedConfiguration.outputFolder
        )
        try FileManager.default.createDirectory(at: outputURL, withIntermediateDirectories: true)

        if verboseConfiguration {
            print(UrkelConfigurationResolver.effectiveConfigurationSummary(
                inputFileURL: inputURL,
                resolved: resolvedConfiguration,
                outputDirectoryURL: outputURL
            ))
        }

        if let tplPath = resolvedConfiguration.templatePath {
            let templateString = try String(contentsOfFile: tplPath, encoding: .utf8)
            var renderFile = file
            if let tplImports = resolvedConfiguration.templateImports, !tplImports.isEmpty {
                renderFile = UrkelFile(
                    machineName: file.machineName,
                    contextType: file.contextType,
                    docComments: file.docComments,
                    imports: tplImports.map { ImportDecl(name: $0) },
                    parallels: file.parallels,
                    states: file.states,
                    entryExitHooks: file.entryExitHooks,
                    transitions: file.transitions,
                    invariants: file.invariants
                )
            }
            let body = try MustacheEmitter().render(file: renderFile, templateString: templateString)
            let fileExtension = resolvedConfiguration.outputExtension ?? inferExtension(fromTemplatePath: tplPath)
            let generatedURL = Self.generatedURL(for: fallbackName, outputExtension: fileExtension, relativeTo: outputURL)
            try body.write(to: generatedURL, atomically: true, encoding: .utf8)
            return [generatedURL]
        } else if let lang = resolvedConfiguration.language {
            var renderFile = file
            if let tplImports = resolvedConfiguration.templateImports, !tplImports.isEmpty {
                renderFile = UrkelFile(
                    machineName: file.machineName,
                    contextType: file.contextType,
                    docComments: file.docComments,
                    imports: tplImports.map { ImportDecl(name: $0) },
                    parallels: file.parallels,
                    states: file.states,
                    entryExitHooks: file.entryExitHooks,
                    transitions: file.transitions,
                    invariants: file.invariants
                )
            }
            let body = try MustacheEmitter().render(file: renderFile, language: lang)
            let fileExtension = resolvedConfiguration.outputExtension ?? defaultExtension(forLanguage: lang)
            let generatedURL = Self.generatedURL(for: fallbackName, outputExtension: fileExtension, relativeTo: outputURL)
            try body.write(to: generatedURL, atomically: true, encoding: .utf8)
            return [generatedURL]
        } else {
            // Native Swift path: emit 3 focused files.
            let emittedFiles = try SwiftSyntaxEmitter().emit(file: file)
            let machineTN = typeName(from: file.machineName)
            let stateMachineURL = outputURL.appendingPathComponent("\(machineTN)Machine.swift")
            let clientURL      = outputURL.appendingPathComponent("\(machineTN)Client.swift")
            let dependencyURL  = outputURL.appendingPathComponent("\(machineTN)Client+Dependency.swift")
            try emittedFiles.stateMachine.write(to: stateMachineURL, atomically: true, encoding: .utf8)
            try emittedFiles.client.write(to: clientURL, atomically: true, encoding: .utf8)
            try emittedFiles.dependency.write(to: dependencyURL, atomically: true, encoding: .utf8)
            return [stateMachineURL, clientURL, dependencyURL]
        }
    }

    public func generateDirectory(
        inputDirectoryPath: String,
        outputPath: String,
        templatePath: String? = nil,
        outputExtension: String? = nil,
        language: String? = nil,
        swiftImports: [String]? = nil,
        templateImports: [String]? = nil,
        additionalConfigSearchDirectories: [URL] = [],
        verboseConfiguration: Bool = false
    ) throws -> [URL] {
        let root = URL(fileURLWithPath: inputDirectoryPath, isDirectory: true)
        guard let enumerator = FileManager.default.enumerator(
            at: root, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]
        ) else { return [] }

        var urkelFiles: [URL] = []
        for case let file as URL in enumerator where file.pathExtension == "urkel" {
            urkelFiles.append(file)
        }

        var outputs: [URL] = []
        for file in urkelFiles {
            let generated = try generate(
                inputPath: file.path,
                outputPath: outputPath,
                templatePath: templatePath,
                outputExtension: outputExtension,
                language: language,
                swiftImports: swiftImports,
                templateImports: templateImports,
                additionalConfigSearchDirectories: additionalConfigSearchDirectories,
                verboseConfiguration: verboseConfiguration
            )
            outputs.append(contentsOf: generated)
        }
        return outputs
    }

    // MARK: - Private helpers

    private func inferExtension(fromTemplatePath path: String) -> String {
        let templateName = URL(fileURLWithPath: path).lastPathComponent
        if templateName.hasSuffix(".mustache") {
            let withoutMustache = String(templateName.dropLast(".mustache".count))
            let ext = URL(fileURLWithPath: withoutMustache).pathExtension
            return ext.isEmpty ? "txt" : ext
        }
        let ext = URL(fileURLWithPath: templateName).pathExtension
        return ext.isEmpty ? "txt" : ext
    }

    private func defaultExtension(forLanguage language: String) -> String {
        switch language.lowercased() {
        case "kotlin": return "kt"
        default:       return "txt"
        }
    }

    private static func generatedURL(
        for fallbackName: String,
        outputExtension: String,
        relativeTo outputURL: URL
    ) -> URL {
        let name = fallbackName + (outputExtension == "swift" ? "+Generated.swift" : ".\(outputExtension)")
        return outputURL.appendingPathComponent(name)
    }

    private static func resolvedOutputDirectoryURL(
        from rootOutputURL: URL,
        configuredOutputFolder: String?
    ) -> URL {
        guard let folder = configuredOutputFolder, !folder.isEmpty else { return rootOutputURL }
        return URL(fileURLWithPath: folder, relativeTo: rootOutputURL).standardizedFileURL
    }

    private func loadBundledTemplate(language: String) throws -> String {
        // Delegate to MustacheEmitter which owns the template bundle
        try MustacheEmitter().render(file: UrkelFile(machineName: "", contextType: nil, docComments: [], imports: [], parallels: [], states: [], entryExitHooks: [], transitions: [], invariants: []), language: language)
    }
}
