import Foundation

public enum UrkelGeneratorError: Error, LocalizedError {
    case fileNotFound(String)
    case notAFile(String)
    case outputFileOnlySupportsSingleInput(String)
    case unsupportedLanguage(String)
    case languageTemplateMissing(String)

    public var errorDescription: String? {
        switch self {
        case .fileNotFound(let path):
            return "Error: File not found at path: \(path)"
        case .notAFile(let path):
            return "Error: Path is not a readable file: \(path)"
        case .outputFileOnlySupportsSingleInput(let path):
            return "Error: The output file option only supports single-file input: \(path)"
        case .unsupportedLanguage(let language):
            return "Unsupported language: \(language)"
        case .languageTemplateMissing(let language):
            return "Bundled template for language '\(language)' was not found."
        }
    }
}

public struct UrkelGenerator {
    public init() {}

    @discardableResult
    public func generatePlaceholder(inputPath: String, outputPath: String) throws -> URL {
        let inputURL = URL(fileURLWithPath: inputPath)
        guard FileManager.default.fileExists(atPath: inputURL.path) else {
            throw UrkelGeneratorError.fileNotFound(inputURL.path)
        }

        var isDirectory = ObjCBool(false)
        guard FileManager.default.fileExists(atPath: inputURL.path, isDirectory: &isDirectory), !isDirectory.boolValue else {
            throw UrkelGeneratorError.notAFile(inputURL.path)
        }

        _ = try String(contentsOf: inputURL, encoding: .utf8)

        let outputURL = URL(fileURLWithPath: outputPath, isDirectory: true)
        try FileManager.default.createDirectory(at: outputURL, withIntermediateDirectories: true)

        let baseName = inputURL.deletingPathExtension().lastPathComponent
        let generatedURL = outputURL.appendingPathComponent("\(baseName)+Generated.swift")
        try "// Placeholder generated by Urkel\n".write(to: generatedURL, atomically: true, encoding: .utf8)
        return generatedURL
    }

    @discardableResult
    public func generate(
        inputPath: String,
        outputPath: String,
        outputFilePath: String? = nil,
        templatePath: String? = nil,
        outputExtension: String? = nil,
        language: String? = nil
    ) throws -> URL {
        let inputURL = URL(fileURLWithPath: inputPath)
        guard FileManager.default.fileExists(atPath: inputURL.path) else {
            throw UrkelGeneratorError.fileNotFound(inputURL.path)
        }

        var isDirectory = ObjCBool(false)
        guard FileManager.default.fileExists(atPath: inputURL.path, isDirectory: &isDirectory), !isDirectory.boolValue else {
            throw UrkelGeneratorError.notAFile(inputURL.path)
        }

        let source = try String(contentsOf: inputURL, encoding: .utf8)
        let fallbackName = inputURL.deletingPathExtension().lastPathComponent

        var ast = try UrkelParser().parse(source: source, machineNameFallback: fallbackName)
        if ast.machineName == "Machine" {
            ast = MachineAST(
                imports: ast.imports,
                machineName: fallbackName,
                contextType: ast.contextType,
                factory: ast.factory,
                states: ast.states,
                transitions: ast.transitions,
                range: ast.range
            )
        }

        try UrkelValidator.validate(ast)

        let outputURL = URL(fileURLWithPath: outputPath, isDirectory: true)
        try FileManager.default.createDirectory(at: outputURL, withIntermediateDirectories: true)

        let body: String
        let generatedURL: URL

        if let templatePath {
            let templateString = try String(contentsOfFile: templatePath, encoding: .utf8)
            body = try MustacheExportEngine().render(ast: ast, templateString: templateString)
            let fileExtension = outputExtension ?? inferExtension(fromTemplatePath: templatePath)
            generatedURL = Self.generatedURL(
                for: fallbackName,
                outputExtension: fileExtension,
                outputFilePath: outputFilePath,
                relativeTo: outputURL
            )
        } else if let language {
            let templateString = try loadBundledTemplate(language: language)
            body = try MustacheExportEngine().render(ast: ast, templateString: templateString)
            let fileExtension = outputExtension ?? defaultExtension(forLanguage: language)
            generatedURL = Self.generatedURL(
                for: fallbackName,
                outputExtension: fileExtension,
                outputFilePath: outputFilePath,
                relativeTo: outputURL
            )
        } else {
            body = UrkelEmitter().emit(ast: ast)
            generatedURL = Self.generatedURL(
                for: fallbackName,
                outputExtension: "swift",
                outputFilePath: outputFilePath,
                relativeTo: outputURL
            )
        }

        if outputFilePath != nil {
            try FileManager.default.createDirectory(
                at: generatedURL.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
        }

        try body.write(to: generatedURL, atomically: true, encoding: .utf8)
        return generatedURL
    }

    public func generateDirectory(
        inputDirectoryPath: String,
        outputPath: String,
        outputFilePath: String? = nil,
        templatePath: String? = nil,
        outputExtension: String? = nil,
        language: String? = nil
    ) throws -> [URL] {
        if let outputFilePath {
            throw UrkelGeneratorError.outputFileOnlySupportsSingleInput(outputFilePath)
        }

        let root = URL(fileURLWithPath: inputDirectoryPath, isDirectory: true)
        guard let enumerator = FileManager.default.enumerator(at: root, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]) else {
            return []
        }

        var outputs: [URL] = []
        for case let file as URL in enumerator where file.pathExtension == "urkel" {
            let generated = try generate(
                inputPath: file.path,
                outputPath: outputPath,
                outputFilePath: nil,
                templatePath: templatePath,
                outputExtension: outputExtension,
                language: language
            )
            outputs.append(generated)
        }
        return outputs
    }

    private func inferExtension(fromTemplatePath path: String) -> String {
        let templateName = URL(fileURLWithPath: path).lastPathComponent
        if templateName.hasSuffix(".mustache") {
            let withoutMustache = String(templateName.dropLast(".mustache".count))
            let ext = URL(fileURLWithPath: withoutMustache).pathExtension
            return ext.isEmpty ? "txt" : ext
        }
        let ext = URL(fileURLWithPath: templateName).pathExtension
        return ext.isEmpty ? "txt" : ext
    }

    private func defaultExtension(forLanguage language: String) -> String {
        switch language.lowercased() {
        case "kotlin":
            return "kt"
        default:
            return "txt"
        }
    }

    private static func generatedURL(
        for fallbackName: String,
        outputExtension: String,
        outputFilePath: String?,
        relativeTo outputURL: URL
    ) -> URL {
        if let outputFilePath {
            return resolvedOutputFileURL(outputFilePath, relativeTo: outputURL)
        }

        let outputName = fallbackName + (outputExtension == "swift" ? "+Generated.swift" : ".\(outputExtension)")
        return outputURL.appendingPathComponent(outputName)
    }

    private static func resolvedOutputFileURL(_ outputFilePath: String, relativeTo outputURL: URL) -> URL {
        if NSString(string: outputFilePath).isAbsolutePath {
            return URL(fileURLWithPath: outputFilePath).standardizedFileURL
        }

        return URL(fileURLWithPath: outputFilePath, relativeTo: outputURL).standardizedFileURL
    }

    private func loadBundledTemplate(language: String) throws -> String {
        let lowered = language.lowercased()
        guard lowered == "kotlin" else {
            throw UrkelGeneratorError.unsupportedLanguage(language)
        }

        guard let url = Bundle.module.url(forResource: lowered, withExtension: "mustache") else {
            throw UrkelGeneratorError.languageTemplateMissing(language)
        }
        return try String(contentsOf: url, encoding: .utf8)
    }
}
